import React, { createContext, useContext, useState, ReactNode } from "react";

// supported languages
export type Lang = "en" | "hi";

const translations = {
  en: {
    home: "Home",
    marketplace: "Marketplace",
    cropAdvisory: "Crop Advisory",
    mspCalculator: "Calculator",
    govSchemes: "Gov Schemes",
    myDashboard: "My Dashboard",
    adminPanel: "Admin Panel",
    loginSignup: "Login / Sign Up",
    logout: "Logout",
    heroTitle: "Kisan Bandhu",
    heroSubtitle: "Empowering Farmers. Connecting Markets.",
    exploreMarketplace: "Explore Marketplace",
    aboutTitle: "About Kisan Bandhu",
    aboutDescription:
      "Kisan Bandhu is India's farmer-first digital marketplace that eliminates middlemen and connects farmers directly with buyers. Our platform ensures fair prices through a transparent bidding system, provides crop advisory services, and helps farmers access government schemes — all in one place.",
    howItWorks: "How It Works",
    readyToGetStarted: "Ready to Get Started?",
    ctaDescription:
      "Join thousands of farmers and buyers on India's most trusted agricultural marketplace.",
    joinKisanBandhu: "Join Kisan Bandhu",
    marketplaceTitle: " Marketplace",
    marketplaceDescription: "Browse and bid on crops from farmers across India",
    pleaseLoginBid: "Please login to place a bid",
    bidSuccess: "Bid placed successfully!",
    onlyBuyer: "Only buyers can place bids.",
    searchPlaceholder: "Search crops...",
    sortLatest: "Latest",
    sortPriceLow: "Price: Low → High",
    sortPriceHigh: "Price: High → Low",
    sortQuantity: "Quantity",
    noCropsFound: "No crops found matching your criteria.",
    welcomeBack: "Welcome Back!",
    createAccountHeader: "Create Account",
    loginPrompt: "Login to your Kisan Bandhu account",
    joinPrompt: "Join Kisan Bandhu today",
    fullNameLabel: "Full Name",
    enterFullName: "Enter your full name",
    emailLabel: "Email",
    enterYourEmail: "Enter your email",
    passwordLabel: "Password",
    enterYourPassword: "Enter your password",
    roleLabel: "I am a",
    farmerRole: "Farmer",
    buyerRole: "Buyer",
    loginButton: "Login",
    createAccountButton: "Create Account",
    dontHaveAccount: "Don't have an account? Sign Up",
    alreadyHaveAccount: "Already have an account? Login",
    errorEmailPassword: "Email and password are required.",
    errorNameRequired: "Name is required.",
    errorPasswordLength: "Password must be at least 6 characters.",
    errorInvalidEmail: "Enter a valid email address.",
    errorInvalidCredentials: "Invalid email or password.",
    errorAccountExists: "Account already exists with this email.",
    governmentSchemesTitle: "🏛️ Government Schemes",
    governmentSchemesDescription: "Important farmer welfare schemes by the Government of India",
    eligibilityLabel: "Eligibility:",
    benefitsLabel: "Benefits:",
    requiredDocuments: "Required Documents",
    docAadhaar: "Aadhaar Card",
    docLand: "Land Record",
    docBank: "Bank Account",
    applyNow: "Apply Now →",
    mspCalculatorTitle: "🧮 Smart Farming Calculator",
    mspSectionTitle: "MSP Calculator",
    mspCalculatorDescription: "Calculate Minimum Support Price value for your harvest",
    selectCropLabel: "Select Crop",
    chooseCropPlaceholder: "Choose a crop",
    quantityLabel: "Quantity (quintals)",
    quantityPlaceholder: "e.g. 50",
    calculateMspButton: "Calculate MSP Value",
    mspResultTitle: "Your MSP Result",
    mspValueLabel: "MSP Value",
    marketBidValueLabel: "Market Bid Value",
    basedOnMarket: "Based on current marketplace",
    marketAbove: "✅ Market bid is ₹{diff} above MSP!",
    marketBelow: "⚠️ Market bid is ₹{diff} below MSP. Consider MSP route.",
    noBidsYet: "No bids yet",
    cropAdvisoryTitle: "🌱 Crop Advisory",
    cropAdvisoryDescription: "Get personalized crop recommendations based on your conditions",
    soilTypeLabel: "Soil Type",
    seasonLabel: "Season",
    regionLabel: "Region",
    selectSoilPlaceholder: "Select Soil",
    selectSeasonPlaceholder: "Select Season",
    selectRegionPlaceholder: "Select Region",
    getRecommendations: "Get Recommendations",
    yieldLabel: "Yield:",
    profitLabel: "Profit:",
    waterLabel: "Water:",
    water_High: "High",
    water_Medium: "Medium",
    water_Low: "Low",
    unit_quintalsPerHectare: "quintals/hectare",
    chooseOption: "Choose an option",
    brandName: "Kisan Bandhu",
    brandDescription: "Empowering farmers by connecting them directly to buyers. Fair prices, transparent bidding, better lives.",
    quickLinks: "Quick Links",
    contactUs: "Contact Us",
    followUs: "Follow Us",
    soil_Alluvial: "Alluvial",
    soil_Black_Regur: "Black (Regur)",
    soil_BlackRegur: "Black (Regur)",
    soil_Red: "Red",
    soil_Laterite: "Laterite",
    soil_Sandy: "Sandy",
    soil_Clay: "Clay",
    season_Kharif: "Kharif (Monsoon)",
    season_Rabi: "Rabi (Winter)",
    season_Zaid: "Zaid (Summer)",
    region_North: "North",
    region_South: "South",
    region_East: "East",
    region_West: "West",
    region_Central: "Central",
    region_NorthEast: "North-East",
    crop_Wheat: "Wheat",
    crop_Rice: "Rice",
    crop_Maize: "Maize",
    crop_Cotton: "Cotton",
    crop_Sugarcane: "Sugarcane",
    crop_Mustard: "Mustard",
    crop_Chickpea_Chana: "Chickpea (Chana)",
    crop_Soybean: "Soybean",
    crop_MoongDal: "Moong Dal",
    crop_Jowar: "Jowar",
    crop_Bajra: "Bajra",
    crop_Groundnut: "Groundnut",

    // ─── RICE ───────────────────────────────────────────────────────────
    riceSowingTime: "June – July (Kharif)",
    riceHarvestTime: "October – November",
    riceSoilPrep: "Puddling is essential. Level field properly for uniform water distribution.",
    riceIrrigation: "Flood irrigation or drip. Needs 1200–2000 mm water over season.",
    riceFertilizer: "120:60:60 kg/ha (NPK). Apply urea in 3 splits.",
    riceTip1: "Transplant seedlings at 20–25 days old for best yield.",
    riceTip2: "Maintain 5 cm standing water during tillering stage.",
    riceTip3: "Use SRI (System of Rice Intensification) for higher yield.",
    riceWarning1: "Watch for Brown Planthopper (BPH) — spray neem-based pesticide.",
    riceWarning2: "Avoid waterlogging for more than 3 days during flowering.",

    // ─── WHEAT ──────────────────────────────────────────────────────────
    wheatSowingTime: "October – November (Rabi)",
    wheatHarvestTime: "March – April",
    wheatSoilPrep: "Deep ploughing followed by 2–3 cultivations. Fine tilth required.",
    wheatIrrigation: "4–6 irrigations. Critical stages: CRI, tillering, jointing, milking.",
    wheatFertilizer: "150:75:60 kg/ha (NPK). Top dress urea at tillering.",
    wheatTip1: "Sow at 100–125 kg/ha seed rate for optimal density.",
    wheatTip2: "First irrigation at crown root initiation (21 days after sowing).",
    wheatTip3: "Use certified rust-resistant varieties like HD-2967 or PBW-550.",
    wheatWarning1: "Yellow rust can devastate yield — apply propiconazole at first sign.",
    wheatWarning2: "Avoid late sowing as it drastically reduces yield.",

    // ─── MAIZE ──────────────────────────────────────────────────────────
    maizeSowingTime: "June – July (Kharif) / Jan–Feb (Rabi)",
    maizeHarvestTime: "September – October",
    maizeSoilPrep: "Well-drained loamy soil best. 2–3 ploughings with FYM incorporation.",
    maizeIrrigation: "5–6 irrigations. Critical at knee-high, tasseling and grain filling.",
    maizeFertilizer: "180:80:60 kg/ha (NPK). Apply in 3 splits.",
    maizeTip1: "Plant at 60×20 cm spacing for good yield.",
    maizeTip2: "Earthing up at 30 days prevents lodging.",
    maizeTip3: "Intercropping with legumes improves soil nitrogen.",
    maizeWarning1: "Fall Armyworm is a serious threat — inspect whorls daily.",
    maizeWarning2: "Avoid waterlogged conditions — maize roots rot quickly.",

    // ─── COTTON ─────────────────────────────────────────────────────────
    cottonSowingTime: "April – May (Kharif)",
    cottonHarvestTime: "October – January",
    cottonSoilPrep: "Deep black soil preferred. Deep ploughing + broad bed furrow system.",
    cottonIrrigation: "8–10 irrigations. Drip irrigation saves water and increases yield.",
    cottonFertilizer: "150:75:75 kg/ha (NPK) + micronutrients like zinc and boron.",
    cottonTip1: "Use Bt cotton varieties to reduce bollworm damage.",
    cottonTip2: "Spray growth regulator (Mepiquat chloride) to control excessive vegetative growth.",
    cottonTip3: "Pick cotton in dry weather to maintain fibre quality.",
    cottonWarning1: "Pink bollworm is most destructive — use pheromone traps.",
    cottonWarning2: "Avoid excess nitrogen — it promotes leaf growth over boll development.",

    // ─── MUSTARD ────────────────────────────────────────────────────────
    mustardSowingTime: "October – November (Rabi)",
    mustardHarvestTime: "February – March",
    mustardSoilPrep: "Well-drained sandy loam preferred. Fine tilth improves germination.",
    mustardIrrigation: "1–2 irrigations sufficient. Avoid excess moisture.",
    mustardFertilizer: "80:40:40 kg/ha (NPK) + sulphur 40 kg/ha for oil quality.",
    mustardTip1: "Thin seedlings to 10–15 cm spacing at 2-week stage.",
    mustardTip2: "One irrigation at branching stage doubles yield.",
    mustardTip3: "Varieties like Pusa Bold and RH-30 give high oil content.",
    mustardWarning1: "Aphid attack in February is common — spray dimethoate.",
    mustardWarning2: "White rust fungus — spray mancozeb at first symptom.",

    // ─── SUGARCANE ──────────────────────────────────────────────────────
    sugarcaneSowingTime: "February – March (Spring) / October (Autumn)",
    sugarcaneHarvestTime: "12–18 months after planting",
    sugarcaneSoilPrep: "Deep ploughing + subsoiling. Furrow planting at 90 cm spacing.",
    sugarcaneIrrigation: "Regular irrigation every 7–10 days. Drip saves 30–40% water.",
    sugarcaneFertilizer: "250:85:120 kg/ha (NPK) in splits over the growing season.",
    sugarcaneTip1: "Use single-eye setts for better germination.",
    sugarcaneTip2: "Trash mulching conserves moisture and controls weeds.",
    sugarcaneTip3: "Ratoon cropping gives good returns with low cost.",
    sugarcaneWarning1: "Red rot is most destructive disease — use disease-free seed material.",
    sugarcaneWarning2: "Top borer and early shoot borer — use carbofuran at planting.",

    // ─── SOYBEAN ────────────────────────────────────────────────────────
    soybeanSowingTime: "June – July (Kharif)",
    soybeanHarvestTime: "September – October",
    soybeanSoilPrep: "Well-drained medium to heavy soil. Avoid compacted soils.",
    soybeanIrrigation: "Rainfed crop mostly. Critical irrigation at flowering if dry spell occurs.",
    soybeanFertilizer: "30:60:40 kg/ha (NPK) + rhizobium culture. Low N as plant fixes own N.",
    soybeanTip1: "Seed treatment with Rhizobium inoculant fixes atmospheric nitrogen.",
    soybeanTip2: "Narrow row spacing (30 cm) increases pod count.",
    soybeanTip3: "Intercropping with sorghum gives stability.",
    soybeanWarning1: "Stem fly and girdle beetle are major pests in early crop.",
    soybeanWarning2: "Excess moisture causes root rot — ensure proper drainage.",

    // ─── GROUNDNUT ──────────────────────────────────────────────────────
    groundnutSowingTime: "June – July (Kharif) / Jan–Feb (Rabi)",
    groundnutHarvestTime: "September – October",
    groundnutSoilPrep: "Sandy loam, well-drained. Deep ploughing + fine tilth essential.",
    groundnutIrrigation: "4–5 irrigations. Avoid irrigation near harvest to prevent aflatoxin.",
    groundnutFertilizer: "20:40:40 kg/ha (NPK) + gypsum 500 kg/ha at flowering.",
    groundnutTip1: "Gypsum application at flowering improves pod filling.",
    groundnutTip2: "Earthing up at 30–40 days helps pegs to penetrate soil.",
    groundnutTip3: "Harvest when inner shell shows dark marks.",
    groundnutWarning1: "Tikka leaf spot — spray chlorothalonil at first appearance.",
    groundnutWarning2: "Aflatoxin contamination risk in dry weather — harvest on time.",

    // ─── DEFAULT ─────────────────────────────────────────────────────────
    defaultSowingTime: "Consult local agricultural officer",
    defaultHarvestTime: "Varies by region and variety",
    defaultSoilPrep: "Standard tillage practices recommended for your soil type.",
    defaultIrrigation: "Based on crop water requirement and local rainfall.",
    defaultFertilizer: "Soil test-based fertilizer application recommended.",
    defaultTip1: "Follow local KVK (Krishi Vigyan Kendra) recommendations.",
    defaultTip2: "Use certified seeds from government-approved sources.",
    defaultTip3: "Maintain crop diary for better planning next season.",
    defaultWarning1: "Monitor regularly for pest and disease symptoms.",
    defaultWarning2: "Check weather forecast before spraying pesticides.",

    // ─── SHARED UI ───────────────────────────────────────────────────────
    sowingTime: "Sowing Time",
    harvestTime: "Harvest Time",
    soilPreparation: "Soil Preparation",
    irrigation: "Irrigation",
    fertilizerRecommendation: "Fertilizer Recommendation",
    expertTips: "Expert Tips",
    warningsWatchouts: "Warnings & Watch-outs",
    fullAdvisory: "Full Advisory",
    completeCropAdvisory: "Complete Crop Advisory",
    close: "Close",

    scheme_PMKISAN_name: "PM-KISAN",
    scheme_PMKISAN_desc: "Direct income support of ₹6,000 per year to farmer families in three equal installments.",
    scheme_PMKISAN_eligibility: "All land-holding farmer families with cultivable land.",
    scheme_PMKISAN_benefits: "₹6,000/year direct bank transfer, no middlemen involved.",
    scheme_PMFasal_name: "PM Fasal Bima Yojana",
    scheme_PMFasal_desc: "Crop insurance scheme providing financial support against crop loss due to natural calamities.",
    scheme_PMFasal_eligibility: "All farmers growing notified crops in notified areas.",
    scheme_PMFasal_benefits: "Low premium rates: 2% for Kharif, 1.5% for Rabi, 5% for commercial crops.",
    scheme_SoilHealth_name: "Soil Health Card Scheme",
    scheme_SoilHealth_desc: "Provides soil health cards with crop-wise nutrient recommendations to farmers.",
    scheme_SoilHealth_eligibility: "All farmers across India.",
    scheme_SoilHealth_benefits: "Free soil testing, personalized fertilizer recommendations, improved yield.",
    scheme_KCC_name: "Kisan Credit Card (KCC)",
    scheme_KCC_desc: "Provides affordable credit to farmers for cultivation, post-harvest, and consumption needs.",
    scheme_KCC_eligibility: "Farmers, fishermen, and animal husbandry farmers.",
    scheme_KCC_benefits: "Credit up to ₹3 lakh at 4% interest, crop insurance coverage included.",
    scheme_eNAM_name: "e-NAM (National Agriculture Market)",
    scheme_eNAM_desc: "Online trading platform for agricultural commodities to ensure better prices for farmers.",
    scheme_eNAM_eligibility: "Registered farmers and traders.",
    scheme_eNAM_benefits: "Transparent price discovery, reduced middlemen, wider market access.",
    scheme_PMKrishi_name: "PM Krishi Sinchai Yojana",
    scheme_PMKrishi_desc: "Ensures access to water for irrigation with 'Har Khet Ko Pani' initiative.",
    scheme_PMKrishi_eligibility: "All farmers with focus on water-scarce areas.",
    scheme_PMKrishi_benefits: "Subsidized micro-irrigation, drip irrigation systems, water harvesting support.",
    scheme_KUSUM_name: "PM KUSUM Yojana",
    scheme_KUSUM_desc: "Supports farmers to install solar pumps and generate additional income.",
    scheme_KUSUM_eligibility: "All farmers interested in solar pump installation.",
    scheme_KUSUM_benefits: "Subsidy on solar pumps, reduced diesel cost, and extra income through solar energy.",
    scheme_AIF_name: "Agriculture Infrastructure Fund",
    scheme_AIF_desc: "Provides financing for warehouses, cold storage, and post-harvest management infrastructure.",
    scheme_AIF_eligibility: "Farmers, FPOs, agri-entrepreneurs, startups, and cooperatives.",
    scheme_AIF_benefits: "Affordable loans, interest subvention, and support for agriculture infrastructure development.",
    scheme_BEE_name: "National Beekeeping & Honey Mission",
    scheme_BEE_desc: "Promotes beekeeping and honey production for additional farmer income.",
    scheme_BEE_eligibility: "Farmers, beekeepers, and interested rural entrepreneurs.",
    scheme_BEE_benefits: "Support for beekeeping equipment, training, and honey production income.",
    farmerDashboardTitle: "🧑‍🌾 Farmer Dashboard",
    buyerDashboardTitle: "🛒 Buyer Dashboard",
    adminPortalTitle: "⚙️ Admin Portal",
    adminPortalDesc: "Platform overview and management",
    welcomeUser: "Welcome, {name}",
    addCrop: "Add Crop",
    listNewCrop: "List a New Crop",
    cropNameLabel: "Crop Name",
    cropNamePlaceholder: "e.g. Wheat",
    cropTypeLabel: "Crop Type",
    cropType_grain: "Grain",
    cropType_vegetable: "Vegetable",
    cropType_fruit: "Fruit",
    cropType_cash_crop: "Cash Crop",
    cropType_pulse: "Pulse",
    market_crop_all: "All Crops",
    market_crop_grain: "🌾 Grains",
    market_crop_vegetable: "🥬 Vegetables",
    market_crop_fruit: "🍎 Fruits",
    market_crop_cash_crop: "🌿 Cash Crops",
    market_crop_pulse: "🫘 Pulses",
    basePriceLabel: "Base Price (₹/quintal)",
    basePricePlaceholder: "e.g. 2200",
    listCropButton: "List Crop",
    cancel: "Cancel",
    status_Open: "Open",
    status_Sold: "Sold",
    viewBids: "Bids",
    acceptBest: "Accept Best",
    errorFillAllFields: "Fill all fields.",
    successCropListed: "Crop listed successfully!",
    successBidAccepted: "Bid accepted! Crop marked as sold.",
    myBidHistory: "My Bid History",
    myBestBidLabel: "My best bid:",
    highestLabel: "Highest:",
    wonStatus: "Won! 🎉",
    lostStatus: "Lost",
    availableCrops: "Available Crops",
    tractorSubsidyTitle: "Tractor Subsidy Calculator",
    tractorPriceLabel: "Tractor Price (₹)",
    enterTractorPrice: "Enter tractor price",
    farmerCategoryLabel: "Farmer Category",
    selectCategory: "Select Category",
    calculateSubsidy: "Calculate Subsidy",
    governmentSubsidy: "Government Subsidy",
    finalPriceAfterSubsidy: "Final Price After Subsidy",
    categoryGeneralFarmer: "General Farmer",
    categorySCSTFarmer: "SC/ST Farmer",
    categoryWomenFarmer: "Women Farmer",
    profitCalculatorTitle: "Profit Calculator",
    sellingPriceLabel: "Selling Price (₹/quintal)",
    sellingPricePlaceholder: "Enter selling price (optional, MSP will be used if empty)",
    productionCostLabel: "Total Production Cost (₹)",
    productionCostPlaceholder: "Enter total production cost",
    calculateProfitButton: "Calculate Profit",
    totalRevenueLabel: "Total Revenue",
    totalCostLabel: "Total Cost",
    netProfitLabel: "Net Profit",
    profitStatus: "Profit",
    lossStatus: "Loss",
    priceUsedLabel: "Price Used",
    usedMspLabel: "MSP Used",
    usedCustomPriceLabel: "Custom Selling Price Used",
    card_base: "Base price:",
    card_highestBid: "Highest bid:",
    card_yourBidPlaceholder: "Your bid (₹)",
    card_bidButton: "Bid",
    successBidPlaced: "Bid placed successfully!",
    admin_statTotalUsers: "Total Users",
    admin_statTotalListings: "Total Listings",
    admin_statTotalBids: "Total Bids",
    admin_statOpenSold: "Open / Sold",
    registeredUsers: "Registered Users",
    nameHeader: "Name",
    emailHeader: "Email",
    roleHeader: "Role",
    noUsersYet: "No users registered yet.",
    allCropListings: "All Crop Listings",
    byLabel: "by",
    listingRemoved: "Listing removed",
    removeBtn: "Remove",
    adminAccessRequired: "Admin access required.",
    bidsSuffix: "bid(s)",
    noListingsMessage: "You haven't listed any crops yet. Click \"Add Crop\" to get started!",
    requiredDocumentsLabel: "Required Documents",
    scheme_PMKISAN_doc1: "Aadhaar Card",
    scheme_PMKISAN_doc2: "Land Record",
    scheme_PMKISAN_doc3: "Bank Account",
    scheme_PMFasal_doc1: "Aadhaar Card",
    scheme_PMFasal_doc2: "Land Record",
    scheme_PMFasal_doc3: "Bank Account",
    scheme_SoilHealth_doc1: "Aadhaar Card",
    scheme_SoilHealth_doc2: "Land Record",
    scheme_SoilHealth_doc3: "Bank Account",
    scheme_KCC_doc1: "Aadhaar Card",
    scheme_KCC_doc2: "Land Record",
    scheme_KCC_doc3: "Bank Account",
    scheme_eNAM_doc1: "Aadhaar Card",
    scheme_eNAM_doc2: "Land Record",
    scheme_eNAM_doc3: "Bank Account",
    scheme_PMKrishi_doc1: "Aadhaar Card",
    scheme_PMKrishi_doc2: "Land Record",
    scheme_PMKrishi_doc3: "Bank Account",
    scheme_KUSUM_doc1: "Aadhaar Card",
    scheme_KUSUM_doc2: "Land Record",
    scheme_KUSUM_doc3: "Bank Account",
    scheme_AIF_doc1: "Aadhaar Card",
    scheme_AIF_doc2: "Land Record",
    scheme_AIF_doc3: "Bank Account",
    scheme_BEE_doc1: "Aadhaar Card",
    scheme_BEE_doc2: "Land Record",
    scheme_BEE_doc3: "Bank Account",
    selectCalculatorTitle: "SELECT A CALCULATOR",
    selectCalculatorSubtitle: "MSP, Subsidy & Profit — smart farming decisions",
    mspCardTitle: "MSP CALCULATOR",
    mspCardDesc: "Calculate Minimum Support Price for your crops and compare with market bids",
    tractorCardTitle: "TRACTOR SUBSIDY",
    tractorCardDesc: "Find out how much government subsidy you can get on tractor purchase",
    profitCardTitle: "PROFIT CALCULATOR",
    profitCardDesc: "Calculate your farming profit based on crop yield, selling price and costs",
    openCalculator: "Open Calculator →",
    subsidyCardTitle: "Tractor Subsidy",
    subsidyCardDesc: "Find out how much government subsidy you can get on tractor purchase",
    stayUpdated: "Stay Updated",
    newsletterText: "Get latest crop prices, schemes & news directly in your inbox!",
    enterEmailPlaceholder: "Enter your email",
    subscribe: "Subscribe",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    supportText: "Support",
    aboutSubtitle: "India's farmer-first digital marketplace — eliminating middlemen, ensuring fair prices, and empowering every kisan.",
    missionTitle: "Our Mission",
    missionText: "To eliminate middlemen and give farmers direct access to buyers — ensuring maximum profit stays with the farmer.",
    visionTitle: "Our Vision",
    visionText: "A digital India where every farmer gets a fair price, transparent trade, and access to government schemes — all in one place.",
    whyTitle: "Why Kisan Bandhu?",
    whyText: "Transparent bidding, crop advisory, MSP calculator, and government schemes — everything a farmer needs, in one platform.",
    featuresTitle: "Key Features",
    featuresSubtitle: "Discover how Kisan Bandhu can benefit farmers, buyers and all agricultural supply chain actors.",
    featureTransparencyTitle: "Transparency",
    featureTransparencyDesc: "Direct transactions between farmers and buyers. No hidden charges, no middlemen.",
    featureFairTradeTitle: "Fair Trade",
    featureFairTradeDesc: "Redistribution of value in the agricultural supply chain. Fair prices for all.",
    featureUserFriendlyTitle: "User Friendly",
    featureUserFriendlyDesc: "Easy to use platform for farmers and buyers. Simple, fast and reliable.",
    featureTraceabilityTitle: "Crop Traceability",
    featureTraceabilityDesc: "Track your crop through the entire supply chain. Coming soon!",
    servicesTitle: "Our Services",
    servicesSubtitle: "Everything a farmer and buyer needs — in one powerful platform.",
    serviceMarketplaceTitle: "Crop Marketplace",
    serviceMarketplaceDesc: "List your crops and get the best bids from verified buyers across India. No middlemen, maximum profit.",
    serviceAdvisoryTitle: "Crop Advisory",
    serviceAdvisoryDesc: "Get expert advice on crop selection, pest control, weather alerts and best farming practices.",
    serviceSchemesTitle: "Gov Schemes",
    serviceSchemesDesc: "Discover and apply for government schemes, subsidies and loans designed for Indian farmers.",
    serviceMspTitle: "MSP Calculator",
    serviceMspDesc: "Calculate Minimum Support Price for your crops instantly. Know your rights, get fair value.",
    serviceSubsidyTitle: "Subsidy Calculator",
    serviceSubsidyDesc: "Calculate government subsidies available for your crops, equipment and farming inputs instantly.",
    serviceInsightsTitle: "Market Insights",
    serviceInsightsDesc: "Real-time crop prices, market trends and demand forecasts to help you make smarter decisions.",
    learnMore: "Learn More",
    valueTitle: "Our Value Proposition",
    valueSubtitle: "Kisan Bandhu connects farmers directly with buyers — eliminating middlemen, ensuring fair prices and transparent trade.",
    networkTitle: "Our Network Across India",
    networkSubtitle: "Farmers and buyers connected across the country — from Kashmir to Kanyakumari.",
    farmerLabel: "Farmer",
    buyerLabel: "Buyer",
    marketInsightsTitle: "Market Insights",
    marketInsightsSubtitle: "Live mandi rates, price trends, state-wise data & weather impact — all in one place.",
    updatedText: "Updated: Today, 9:00 AM",
    panIndia: "Pan India Data",
    cropsTracked: "12 Crops Tracked",
    livePrices: "Live Prices",
    priceCharts: "Price Charts",
    stateWise: "State Wise",
    demandTrends: "Demand Trends",
    weatherImpact: "Weather Impact",
    liveMandiRates: "Live Mandi Rates",
    demoData: "Demo Data",
    highDemand: "High Demand",
    mediumDemand: "Medium Demand",
    veryHighDemand: "Very High Demand",
    stableDemand: "Stable Demand",
    Wheat: "Wheat",
    "Rice (Basmati)": "Rice (Basmati)",
    Cotton: "Cotton",
    Soybean: "Soybean",
    Maize: "Maize",
    Tomato: "Tomato",
    Onion: "Onion",
    Potato: "Potato",
    Sugarcane: "Sugarcane",
    Turmeric: "Turmeric",
    Chilli: "Chilli",
    Groundnut: "Groundnut",
    cropWheat: "Wheat",
    cropRiceBasmati: "Rice (Basmati)",
    cropCotton: "Cotton",
    cropSoybean: "Soybean",
    cropMaize: "Maize",
    cropTomato: "Tomato",
    cropOnion: "Onion",
    cropPotato: "Potato",
    cropSugarcane: "Sugarcane",
    cropTurmeric: "Turmeric",
    cropChilli: "Chilli",
    cropGroundnut: "Groundnut",
    priceTrendOctMar: "Price Trend (Oct–Mar)",
    sixMonthPriceTrends: "6-Month Price Trends",
    selectCropPriceHistory: "Select a crop to view its price history",
    stateWiseCropPrices: "State Wise Crop Prices",
    topCrop: "Top Crop",
    rising: "Rising",
    falling: "Falling",
    demandSupplyTrends: "Demand & Supply Trends",
    demandLabel: "Demand",
    supplyLabel: "Supply",
    weatherImpactCrops: "Weather Impact on Crops",
    favorable: "Favorable",
    riskAlert: "Risk Alert",
    monitor: "Monitor",
    weeklyFarmingAdvisory: "Weekly Farming Advisory",
    sowNow: "Sow Now",
    sowNowCrops: "Tomato, Onion, Green Vegetables",
    harvestReady: "Harvest Ready",
    harvestReadyCrops: "Wheat, Mustard, Gram",
    avoidThisWeek: "Avoid This Week",
    avoidThisWeekCrops: "Cotton in heavy rain regions",
    northIndia: "North India",
    southIndia: "South India",
    eastIndia: "East India",
    westIndia: "West India",
    centralIndia: "Central India",
    clear: "Clear",
    heavyRain: "Heavy Rain",
    partlyCloudy: "Partly Cloudy",
    sunny: "Sunny",
    intermittentRain: "Intermittent Rain",
    wheatHarvestGood: "Good for Wheat harvest",
    cottonRisk: "Risk for Cotton & Chilli",
    riceModerate: "Moderate for Rice",
    groundnutGood: "Good for Groundnut",
    soybeanWatch: "Watch Soybean moisture",
    statePunjab: "Punjab",
    stateUttarPradesh: "Uttar Pradesh",
    stateMaharashtra: "Maharashtra",
    stateMadhyaPradesh: "Madhya Pradesh",
    stateAndhraPradesh: "Andhra Pradesh",
    stateKarnataka: "Karnataka",
    stateGujarat: "Gujarat",
    stateWestBengal: "West Bengal",
    backToCalculators: "Back to Calculators",
    tractorSubsidySubtitle: "Calculate government subsidy on tractor purchase",
    profitCalculatorSubtitle: "Calculate your net farming profit",
    quantityQuintalsLabel: "Quantity (quintals)",
    profitResultTitle: "Your Profit Result",
    mspPriceUsedLabel: "MSP price used",
    revenueLabel: "Revenue",
    costLabel: "Cost",
    lossLabel: "Loss",
    calculateProfit: "Calculate Profit",
    region_North_East: "North-East",
    marketInsights: "Market Insights",
    joinNow: "Join Now",
    statesCovered: "States Covered",
    farmersCount: "Farmers",
    buyersCount: "Buyers",
    marketBidLabel: "Market Bid",
    noBids: "No Bids",
    basedOnMarketplace: "Based on Marketplace",
    subsidyResultTitle: "Subsidy Result",
    subsidySavedMessage: "You saved ₹{amount}",
    marketplaceSubtitle: "Browse and bid on fresh crops directly from farmers across India",
    totalListings: "Total Listings",
    openForBids: "Open for Bids",
    totalBids: "Total Bids",
    searchCropsPlaceholder: "Search crops...",
    latest: "Latest",
    priceLowHigh: "Price: Low to High",
    priceHighLow: "Price: High to Low",
    byQuantity: "By Quantity",
    allCrops: "All Crops",
    grains: "Grains",
    vegetables: "Vegetables",
    fruits: "Fruits",
    cashCrops: "Cash Crops",
    pulses: "Pulses",
    showingListings: "Showing {count} listings",
    sortedBy: "Sorted by:",
    noListingsAvailable: "No listings available right now",
    listCropsMessage: "List your crops from your dashboard!",
    "price-low": "Price: Low to High",
    "price-high": "Price: High to Low",
    quantity: "By Quantity",
    yield: "Yield",
    profit: "Profit",
    water: "Water",
  },

  hi: {
    home: "होम",
    marketplace: "मार्केटप्लेस",
    cropAdvisory: "फसल सलाह",
    mspCalculator: "कैलकुलेटर",
    subsidyCalculator: "सब्सिडी कैल्क्युलेटर",
    govSchemes: "सरकारी योजनाएँ",
    myDashboard: "मेरा डैशबोर्ड",
    adminPanel: "प्रशासन पैनल",
    loginSignup: "लॉगिन / साइन अप",
    logout: "लॉगआउट",
    heroTitle: "किसान बंधु",
    heroSubtitle: "आपकी फ़सलें। आपकी क़ीमत। आपकी ताक़त।",
    exploreMarketplace: "मार्केटप्लेस देखें",
    aboutTitle: "किसान बंधु के बारे में",
    aboutDescription:
      "किसान बंधु भारत का किसान-प्रथम डिजिटल मार्केटप्लेस है जो दलालों को हटाकर किसानों को सीधे खरीदारों से जोड़ता है।",
    howItWorks: "यह कैसे काम करता है",
    readyToGetStarted: "शुरू करने के लिए तैयार?",
    ctaDescription: "भारत के सबसे विश्वसनीय कृषि बाजार पर हजारों किसानों और खरीदारों से जुड़ें।",
    joinKisanBandhu: "किसान बंधु में शामिल हों",
    marketplaceTitle: " मार्केटप्लेस",
    marketplaceDescription: "भारत भर के किसानों से फसलों पर नीलामी करें और बोली लगाएं",
    pleaseLoginBid: "बोली लगाने के लिए कृपया लॉगिन करें",
    bidSuccess: "बोली सफलतापूर्वक लगाई गई!",
    onlyBuyer: "केवल खरीदार बोली लगा सकते हैं।",
    searchPlaceholder: "फसलों की खोज करें...",
    sortLatest: "नवीनतम",
    sortPriceLow: "कीमत: कम → अधिक",
    sortPriceHigh: "कीमत: अधिक → कम",
    sortQuantity: "मात्रा",
    noCropsFound: "आपकी शर्तों के अनुरूप कोई फसल नहीं मिली।",
    welcomeBack: "वापसी पर स्वागत है!",
    createAccountHeader: "खाता बनाएं",
    loginPrompt: "अपने किसान बंधु खाते में लॉगिन करें",
    joinPrompt: "आज किसान बंधु में शामिल हों",
    fullNameLabel: "पूरा नाम",
    enterFullName: "अपना पूरा नाम दर्ज करें",
    emailLabel: "ईमेल",
    enterYourEmail: "अपना ईमेल दर्ज करें",
    passwordLabel: "पासवर्ड",
    enterYourPassword: "अपना पासवर्ड दर्ज करें",
    roleLabel: "मैं एक हूँ",
    farmerRole: "किसान",
    buyerRole: "खरीदार",
    loginButton: "लॉगिन",
    createAccountButton: "खाता बनाएं",
    dontHaveAccount: "खाता नहीं है? साइन अप करें",
    alreadyHaveAccount: "पहले से एक खाता है? लॉगिन करें",
    errorEmailPassword: "ईमेल और पासवर्ड आवश्यक हैं।",
    errorNameRequired: "नाम आवश्यक है।",
    errorPasswordLength: "पासवर्ड कम से कम 6 अक्षरों का होना चाहिए।",
    errorInvalidEmail: "एक वैध ईमेल पता दर्ज करें।",
    errorInvalidCredentials: "अमान्य ईमेल या पासवर्ड।",
    errorAccountExists: "इस ईमेल के साथ पहले से एक खाता मौजूद है।",
    governmentSchemesTitle: "🏛️ सरकारी योजनाएँ",
    governmentSchemesDescription: "भारत सरकार द्वारा महत्वपूर्ण किसान कल्याण योजनाएँ",
    eligibilityLabel: "योग्यता:",
    benefitsLabel: "लाभ:",
    requiredDocuments: "आवश्यक दस्तावेज",
    docAadhaar: "आधार कार्ड",
    docLand: "भूमि अभिलेख",
    docBank: "बैंक खाता",
    applyNow: "अब आवेदन करें →",
    mspCalculatorTitle: "🧮 स्मार्ट फार्मिंग कैलकुलेटर",
    mspSectionTitle: "एमएसपी कैलकुलेटर",
    mspCalculatorDescription: "अपने फसल के लिए न्यूनतम समर्थन मूल्य की गणना करें",
    selectCropLabel: "फसल चुनें",
    chooseCropPlaceholder: "फसल चुनें",
    quantityLabel: "मात्रा (क्विंटल)",
    quantityPlaceholder: "जैसे 50",
    calculateMspButton: "एमएसपी मान की गणना करें",
    mspResultTitle: "आपका एमएसपी परिणाम",
    mspValueLabel: "एमएसपी मूल्य",
    marketBidValueLabel: "बाजार बोली मूल्य",
    basedOnMarket: "वर्तमान बाज़ार के आधार पर",
    marketAbove: "✅ बाजार बोली MSP से ₹{diff} ऊपर है!",
    marketBelow: "⚠️ बाजार बोली MSP से ₹{diff} नीचे है। MSP मार्ग पर विचार करें।",
    noBidsYet: "अभी तक कोई बोली नहीं",
    cropAdvisoryTitle: "🌱 फसल सलाह",
    cropAdvisoryDescription: "आपकी परिस्थितियों के आधार पर व्यक्तिगत रूप से फसल की सिफारिशें प्राप्त करें",
    soilTypeLabel: "मिट्टी का प्रकार",
    seasonLabel: "मौसम",
    regionLabel: "क्षेत्र",
    selectSoilPlaceholder: "मिट्टी चुनें",
    selectSeasonPlaceholder: "मौसम चुनें",
    selectRegionPlaceholder: "क्षेत्र चुनें",
    getRecommendations: "अनुशंसाएँ प्राप्त करें",
    yieldLabel: "उपज:",
    profitLabel: "लाभ:",
    waterLabel: "पानी:",
    water_High: "उच्च",
    water_Medium: "मध्यम",
    water_Low: "निम्न",
    unit_quintalsPerHectare: "क्विंटल/हेक्टेयर",
    chooseOption: "एक विकल्प चुनें",
    brandName: "किसान बंधु",
    brandDescription: "किसानों को सीधे खरीदारों से जोड़कर उन्हें सशक्त बनाना।",
    quickLinks: "त्वरित लिंक",
    contactUs: "संपर्क करें",
    followUs: "हमें फॉलो करें",
    soil_Alluvial: "जलोढ़ मिट्टी",
    soil_Black_Regur: "काली (रेगूर) मिट्टी",
    soil_BlackRegur: "काली (रेगूर) मिट्टी",
    soil_Red: "लाल मिट्टी",
    soil_Laterite: "लेटेराइट मिट्टी",
    soil_Sandy: "रेतीली मिट्टी",
    soil_Clay: "चिकनी मिट्टी",
    season_Kharif: "खरीफ (मानसून)",
    season_Rabi: "रबी (सर्दी)",
    season_Zaid: "ज़ैद (गर्मी)",
    region_North: "उत्तर",
    region_South: "दक्षिण",
    region_East: "पूर्व",
    region_West: "पश्चिम",
    region_Central: "केंद्रीय",
    region_NorthEast: "उत्तर-पूर्व",
    crop_Wheat: "गेहूँ",
    crop_Rice: "चावल",
    crop_Maize: "मक्का",
    crop_Cotton: "कपास",
    crop_Sugarcane: "गन्ना",
    crop_Mustard: "सरसों",
    crop_Chickpea_Chana: "चना (काबुली)",
    crop_Soybean: "सोयाबीन",
    crop_MoongDal: "मूंग दाल",
    crop_Jowar: "ज्वार",
    crop_Bajra: "बाजरा",
    crop_Groundnut: "मूंगफली",

    // ─── RICE ───────────────────────────────────────────────────────────
    riceSowingTime: "जून – जुलाई (खरीफ)",
    riceHarvestTime: "अक्टूबर – नवंबर",
    riceSoilPrep: "पडलिंग आवश्यक है। पानी के समान वितरण के लिए खेत को समतल करें।",
    riceIrrigation: "बाढ़ सिंचाई या ड्रिप। पूरे मौसम में 1200–2000 मिमी पानी की आवश्यकता होती है।",
    riceFertilizer: "120:60:60 किग्रा/हेक्टेयर (NPK)। यूरिया को 3 भागों में डालें।",
    riceTip1: "बेहतर उपज के लिए 20–25 दिन के पौधों का रोपण करें।",
    riceTip2: "टिलरिंग चरण के दौरान 5 सेमी खड़ा पानी बनाए रखें।",
    riceTip3: "अधिक उपज के लिए SRI (चावल गहनता प्रणाली) अपनाएं।",
    riceWarning1: "ब्राउन प्लांटहॉपर (BPH) से सावधान — नीम आधारित कीटनाशक का छिड़काव करें।",
    riceWarning2: "फूल आने के दौरान 3 दिन से अधिक जलभराव से बचें।",

    // ─── WHEAT ──────────────────────────────────────────────────────────
    wheatSowingTime: "अक्टूबर – नवंबर (रबी)",
    wheatHarvestTime: "मार्च – अप्रैल",
    wheatSoilPrep: "गहरी जुताई के बाद 2–3 बार खेत तैयार करें। बारीक मिट्टी आवश्यक है।",
    wheatIrrigation: "4–6 सिंचाई। महत्वपूर्ण चरण: CRI, टिलरिंग, जोड़ बनना, दूध भरना।",
    wheatFertilizer: "150:75:60 किग्रा/हेक्टेयर (NPK)। टिलरिंग पर यूरिया का ऊपरी छिड़काव करें।",
    wheatTip1: "सर्वोत्तम घनत्व के लिए 100–125 किग्रा/हेक्टेयर की दर से बोएं।",
    wheatTip2: "बुवाई के 21 दिन बाद ताज की जड़ उगने पर पहली सिंचाई करें।",
    wheatTip3: "HD-2967 या PBW-550 जैसी रोग-प्रतिरोधी प्रमाणित किस्में उपयोग करें।",
    wheatWarning1: "पीला रतुआ उपज को नष्ट कर सकता है — पहले लक्षण पर प्रोपिकोनाज़ोल का छिड़काव करें।",
    wheatWarning2: "देर से बुवाई से उपज में भारी कमी आती है — समय पर बोएं।",

    // ─── MAIZE ──────────────────────────────────────────────────────────
    maizeSowingTime: "जून – जुलाई (खरीफ) / जनवरी–फरवरी (रबी)",
    maizeHarvestTime: "सितंबर – अक्टूबर",
    maizeSoilPrep: "अच्छी जल निकासी वाली दोमट मिट्टी उत्तम है। FYM के साथ 2–3 बार जुताई करें।",
    maizeIrrigation: "5–6 सिंचाई। घुटने तक ऊंचाई, टैसलिंग और दाना भरने पर विशेष ध्यान दें।",
    maizeFertilizer: "180:80:60 किग्रा/हेक्टेयर (NPK)। 3 भागों में डालें।",
    maizeTip1: "अच्छी उपज के लिए 60×20 सेमी की दूरी पर रोपण करें।",
    maizeTip2: "30 दिन पर मिट्टी चढ़ाने से पौधा गिरने से बचता है।",
    maizeTip3: "दलहनी फसलों के साथ अंतर-फसल से मिट्टी की नाइट्रोजन बढ़ती है।",
    maizeWarning1: "फॉल आर्मीवर्म गंभीर खतरा है — प्रतिदिन पत्तियों की जांच करें।",
    maizeWarning2: "जलभराव से बचें — मक्का की जड़ें जल्दी सड़ती हैं।",

    // ─── COTTON ─────────────────────────────────────────────────────────
    cottonSowingTime: "अप्रैल – मई (खरीफ)",
    cottonHarvestTime: "अक्टूबर – जनवरी",
    cottonSoilPrep: "गहरी काली मिट्टी उपयुक्त है। गहरी जुताई + चौड़ी क्यारी-नाली विधि अपनाएं।",
    cottonIrrigation: "8–10 सिंचाई। ड्रिप सिंचाई से पानी की बचत और उपज में वृद्धि होती है।",
    cottonFertilizer: "150:75:75 किग्रा/हेक्टेयर (NPK) + जिंक और बोरॉन जैसे सूक्ष्म पोषक तत्व।",
    cottonTip1: "बॉलवर्म नुकसान कम करने के लिए Bt कपास किस्में उपयोग करें।",
    cottonTip2: "अत्यधिक वानस्पतिक वृद्धि नियंत्रित करने के लिए ग्रोथ रेगुलेटर (मेपीक्वाट क्लोराइड) का छिड़काव करें।",
    cottonTip3: "रेशे की गुणवत्ता बनाए रखने के लिए सूखे मौसम में कपास की चुनाई करें।",
    cottonWarning1: "गुलाबी बॉलवर्म सबसे विनाशकारी है — फेरोमोन ट्रैप का उपयोग करें।",
    cottonWarning2: "अत्यधिक नाइट्रोजन से बचें — इससे टिंडे के बजाय पत्तियां अधिक बढ़ती हैं।",

    // ─── MUSTARD ────────────────────────────────────────────────────────
    mustardSowingTime: "अक्टूबर – नवंबर (रबी)",
    mustardHarvestTime: "फरवरी – मार्च",
    mustardSoilPrep: "अच्छी जल निकासी वाली रेतीली दोमट मिट्टी उपयुक्त। बारीक तैयारी से अंकुरण बेहतर होता है।",
    mustardIrrigation: "1–2 सिंचाई पर्याप्त। अधिक नमी से बचें।",
    mustardFertilizer: "80:40:40 किग्रा/हेक्टेयर (NPK) + तेल की गुणवत्ता के लिए 40 किग्रा/हेक्टेयर सल्फर।",
    mustardTip1: "2 सप्ताह की अवस्था में पौधों को 10–15 सेमी की दूरी पर छांटें।",
    mustardTip2: "शाखाएं निकलते समय एक सिंचाई से उपज दोगुनी हो जाती है।",
    mustardTip3: "पूसा बोल्ड और RH-30 जैसी किस्में अधिक तेल देती हैं।",
    mustardWarning1: "फरवरी में माहू का प्रकोप सामान्य है — डाइमेथोएट का छिड़काव करें।",
    mustardWarning2: "सफेद रतुआ फफूंद — पहले लक्षण पर मैंकोजेब का छिड़काव करें।",

    // ─── SUGARCANE ──────────────────────────────────────────────────────
    sugarcaneSowingTime: "फरवरी – मार्च (वसंत) / अक्टूबर (शरद)",
    sugarcaneHarvestTime: "रोपण के 12–18 महीने बाद",
    sugarcaneSoilPrep: "गहरी जुताई + उप-मृदा जुताई। 90 सेमी की दूरी पर कूंड में रोपण।",
    sugarcaneIrrigation: "हर 7–10 दिन में नियमित सिंचाई। ड्रिप से 30–40% पानी की बचत होती है।",
    sugarcaneFertilizer: "250:85:120 किग्रा/हेक्टेयर (NPK) को बढ़ती मौसम में भागों में डालें।",
    sugarcaneTip1: "बेहतर अंकुरण के लिए एकल आंख वाले सेट्स का उपयोग करें।",
    sugarcaneTip2: "पत्ती पलवार से नमी बचती है और खरपतवार नियंत्रण होता है।",
    sugarcaneTip3: "रैटून फसल से कम लागत में अच्छा मुनाफा मिलता है।",
    sugarcaneWarning1: "लाल सड़न सबसे विनाशकारी रोग है — रोगमुक्त बीज सामग्री का उपयोग करें।",
    sugarcaneWarning2: "शीर्ष छेदक और प्रारंभिक तना छेदक — रोपण पर कार्बोफ्यूरान का उपयोग करें।",

    // ─── SOYBEAN ────────────────────────────────────────────────────────
    soybeanSowingTime: "जून – जुलाई (खरीफ)",
    soybeanHarvestTime: "सितंबर – अक्टूबर",
    soybeanSoilPrep: "अच्छी जल निकासी वाली मध्यम से भारी मिट्टी। दबी हुई मिट्टी से बचें।",
    soybeanIrrigation: "मुख्यतः वर्षा आधारित फसल। सूखे के दौरान फूल आने पर सिंचाई करें।",
    soybeanFertilizer: "30:60:40 किग्रा/हेक्टेयर (NPK) + राइजोबियम कल्चर। पौधा स्वयं नाइट्रोजन बनाता है।",
    soybeanTip1: "राइजोबियम टीके से बीज उपचार से वायुमंडलीय नाइट्रोजन स्थिर होती है।",
    soybeanTip2: "संकरी पंक्ति दूरी (30 सेमी) से फलियों की संख्या बढ़ती है।",
    soybeanTip3: "ज्वार के साथ अंतर-फसल से स्थिरता मिलती है।",
    soybeanWarning1: "तना मक्खी और करधनी भृंग प्रारंभिक फसल में प्रमुख कीट हैं।",
    soybeanWarning2: "अधिक नमी से जड़ सड़न होती है — उचित जल निकासी सुनिश्चित करें।",

    // ─── GROUNDNUT ──────────────────────────────────────────────────────
    groundnutSowingTime: "जून – जुलाई (खरीफ) / जनवरी–फरवरी (रबी)",
    groundnutHarvestTime: "सितंबर – अक्टूबर",
    groundnutSoilPrep: "रेतीली दोमट, अच्छी जल निकासी वाली मिट्टी। गहरी जुताई + बारीक तैयारी आवश्यक।",
    groundnutIrrigation: "4–5 सिंचाई। अफलाटॉक्सिन रोकने के लिए कटाई के पास सिंचाई न करें।",
    groundnutFertilizer: "20:40:40 किग्रा/हेक्टेयर (NPK) + फूल आने पर 500 किग्रा/हेक्टेयर जिप्सम।",
    groundnutTip1: "फूल आने पर जिप्सम डालने से फली भरना बेहतर होता है।",
    groundnutTip2: "30–40 दिन पर मिट्टी चढ़ाने से खूंटियाँ मिट्टी में घुसती हैं।",
    groundnutTip3: "जब खोल के अंदर काले निशान दिखें तब खुदाई करें।",
    groundnutWarning1: "टिक्का पत्ती धब्बा — पहले लक्षण पर क्लोरोथेलोनिल का छिड़काव करें।",
    groundnutWarning2: "सूखे मौसम में अफलाटॉक्सिन का खतरा — समय पर कटाई करें।",

    // ─── DEFAULT ─────────────────────────────────────────────────────────
    defaultSowingTime: "स्थानीय कृषि अधिकारी से परामर्श लें",
    defaultHarvestTime: "क्षेत्र और किस्म के अनुसार भिन्न",
    defaultSoilPrep: "अपनी मिट्टी के प्रकार के लिए मानक जुताई पद्धतियाँ अनुशंसित हैं।",
    defaultIrrigation: "फसल की जल आवश्यकता और स्थानीय वर्षा के आधार पर।",
    defaultFertilizer: "मिट्टी परीक्षण आधारित उर्वरक प्रयोग की अनुशंसा की जाती है।",
    defaultTip1: "स्थानीय KVK (कृषि विज्ञान केंद्र) की सिफारिशों का पालन करें।",
    defaultTip2: "सरकार अनुमोदित स्रोतों से प्रमाणित बीज का उपयोग करें।",
    defaultTip3: "बेहतर योजना के लिए फसल डायरी बनाए रखें।",
    defaultWarning1: "कीट और रोग के लक्षणों के लिए नियमित निगरानी करें।",
    defaultWarning2: "कीटनाशक छिड़काव से पहले मौसम का पूर्वानुमान देखें।",

    // ─── SHARED UI ───────────────────────────────────────────────────────
    sowingTime: "बुवाई का समय",
    harvestTime: "कटाई का समय",
    soilPreparation: "मिट्टी की तैयारी",
    irrigation: "सिंचाई",
    fertilizerRecommendation: "उर्वरक सिफारिश",
    expertTips: "विशेषज्ञ सुझाव",
    warningsWatchouts: "चेतावनियाँ और सावधानियाँ",
    fullAdvisory: "पूरी सलाह",
    completeCropAdvisory: "पूर्ण फसल सलाह",
    close: "बंद करें",

    scheme_PMKISAN_name: "पीएम-किसान",
    scheme_PMKISAN_desc: "किसान परिवारों को तीन समान किस्तों में प्रति वर्ष ₹6,000 की प्रत्यक्ष आय सहायता।",
    scheme_PMKISAN_eligibility: "खेती योग्य भूमि वाले सभी किसान परिवार।",
    scheme_PMKISAN_benefits: "₹6,000 प्रति वर्ष सीधे बैंक खाते में, बिना किसी दलाल के।",
    scheme_PMFasal_name: "प्रधानमंत्री फसल बीमा योजना",
    scheme_PMFasal_desc: "प्राकृतिक आपदाओं के कारण फसल नुकसान के खिलाफ वित्तीय सहायता प्रदान करने वाली फसल बीमा योजना।",
    scheme_PMFasal_eligibility: "अधिसूचित क्षेत्रों में अधिसूचित फसलें उगाने वाले सभी किसान।",
    scheme_PMFasal_benefits: "कम प्रीमियम दरें: खरीफ के लिए 2%, रबी के लिए 1.5%, वाणिज्यिक फसलों के लिए 5%।",
    scheme_SoilHealth_name: "मृदा स्वास्थ्य कार्ड योजना",
    scheme_SoilHealth_desc: "किसानों को फसल-वार पोषक तत्व सिफारिशों के साथ मृदा स्वास्थ्य कार्ड प्रदान करती है।",
    scheme_SoilHealth_eligibility: "भारत के सभी किसान।",
    scheme_SoilHealth_benefits: "मुफ्त मिट्टी परीक्षण, व्यक्तिगत उर्वरक सिफारिशें और बेहतर उपज।",
    scheme_KCC_name: "किसान क्रेडिट कार्ड (KCC)",
    scheme_KCC_desc: "खेती, फसल कटाई के बाद की जरूरतों और अन्य आवश्यकताओं के लिए सुलभ ऋण प्रदान करता है।",
    scheme_KCC_eligibility: "किसान, मछुआरे और पशुपालक किसान।",
    scheme_KCC_benefits: "₹3 लाख तक 4% ब्याज पर ऋण तथा फसल बीमा कवर।",
    scheme_eNAM_name: "ई-नाम (राष्ट्रीय कृषि बाजार)",
    scheme_eNAM_desc: "किसानों को बेहतर मूल्य दिलाने के लिए कृषि उपज का ऑनलाइन व्यापार मंच।",
    scheme_eNAM_eligibility: "पंजीकृत किसान और व्यापारी।",
    scheme_eNAM_benefits: "पारदर्शी मूल्य खोज, कम दलाल और व्यापक बाजार पहुंच।",
    scheme_PMKrishi_name: "प्रधानमंत्री कृषि सिंचाई योजना",
    scheme_PMKrishi_desc: "'हर खेत को पानी' पहल के तहत सिंचाई के लिए पानी की उपलब्धता सुनिश्चित करती है।",
    scheme_PMKrishi_eligibility: "विशेष रूप से जल-संकट क्षेत्रों सहित सभी किसान।",
    scheme_PMKrishi_benefits: "सब्सिडी वाली माइक्रो-सिंचाई, ड्रिप सिस्टम और जल संचयन सहायता।",
    scheme_KUSUM_name: "पीएम कुसुम योजना",
    scheme_KUSUM_desc: "किसानों को सोलर पंप लगाने और अतिरिक्त आय अर्जित करने में सहायता प्रदान करती है।",
    scheme_KUSUM_eligibility: "सोलर पंप स्थापना में रुचि रखने वाले सभी किसान।",
    scheme_KUSUM_benefits: "सोलर पंप पर सब्सिडी, डीजल खर्च में कमी और सौर ऊर्जा से अतिरिक्त आय।",
    scheme_AIF_name: "कृषि अवसंरचना निधि",
    scheme_AIF_desc: "वेयरहाउस, कोल्ड स्टोरेज और कटाई के बाद की कृषि अवसंरचना के लिए वित्तीय सहायता।",
    scheme_AIF_eligibility: "किसान, एफपीओ, कृषि उद्यमी, स्टार्टअप और सहकारी संस्थाएँ।",
    scheme_AIF_benefits: "सस्ती ऋण सुविधा, ब्याज में छूट और कृषि अवसंरचना विकास हेतु सहायता।",
    scheme_BEE_name: "राष्ट्रीय मधुमक्खी पालन एवं शहद मिशन",
    scheme_BEE_desc: "अतिरिक्त किसान आय के लिए मधुमक्खी पालन और शहद उत्पादन को बढ़ावा देता है।",
    scheme_BEE_eligibility: "किसान, मधुमक्खी पालक और इच्छुक ग्रामीण उद्यमी।",
    scheme_BEE_benefits: "मधुमक्खी पालन उपकरण, प्रशिक्षण और शहद उत्पादन से आय हेतु सहायता।",
    farmerDashboardTitle: "🧑‍🌾 किसान डैशबोर्ड",
    buyerDashboardTitle: "🛒 खरीदार डैशबोर्ड",
    adminPortalTitle: "⚙️ प्रशासन पोर्टल",
    adminPortalDesc: "प्लेटफ़ॉर्म अवलोकन और प्रबंधन",
    welcomeUser: "स्वागत है, {name}",
    addCrop: "फसल जोड़ें",
    listNewCrop: "नई फसल सूचीबद्ध करें",
    cropNameLabel: "फसल का नाम",
    cropNamePlaceholder: "जैसे गेहूँ",
    cropTypeLabel: "फसल का प्रकार",
    cropType_grain: "अनाज",
    cropType_vegetable: "सब्ज़ी",
    cropType_fruit: "फल",
    cropType_cash_crop: "नकदी फसल",
    cropType_pulse: "दाल",
    market_crop_all: "सभी फसलें",
    market_crop_grain: "🌾 अनाज",
    market_crop_vegetable: "🥬 सब्ज़ियाँ",
    market_crop_fruit: "🍎 फल",
    market_crop_cash_crop: "🌿 नकदी फसलें",
    market_crop_pulse: "🫘 दालें",
    basePriceLabel: "मूल्य (₹/क्विंटल)",
    basePricePlaceholder: "जैसे 2200",
    listCropButton: "फसल सूचीबद्ध करें",
    cancel: "रद्द करें",
    status_Open: "खुला",
    status_Sold: "बिक चुका",
    viewBids: "बोली",
    acceptBest: "सर्वोत्तम स्वीकार करें",
    errorFillAllFields: "सभी फ़ील्ड भरें।",
    successCropListed: "फसल सफलतापूर्वक सूचीबद्ध की गई!",
    successBidAccepted: "बोली स्वीकार की गई! फसल बेची हुई के रूप में चिह्नित।",
    myBidHistory: "मेरी बोली इतिहास",
    myBestBidLabel: "मेरी सर्वोत्तम बोली:",
    highestLabel: "सर्वोच्च:",
    wonStatus: "जीत गए! 🎉",
    lostStatus: "हार गए",
    availableCrops: "उपलब्ध फसलें",
    tractorSubsidyTitle: "ट्रैक्टर सब्सिडी कैलकुलेटर",
    tractorPriceLabel: "ट्रैक्टर की कीमत (₹)",
    enterTractorPrice: "ट्रैक्टर की कीमत दर्ज करें",
    farmerCategoryLabel: "किसान श्रेणी",
    selectCategory: "श्रेणी चुनें",
    calculateSubsidy: "सब्सिडी की गणना करें",
    governmentSubsidy: "सरकारी सब्सिडी",
    finalPriceAfterSubsidy: "सब्सिडी के बाद अंतिम कीमत",
    categoryGeneralFarmer: "सामान्य किसान",
    categorySCSTFarmer: "अनुसूचित जाति / अनुसूचित जनजाति किसान",
    categoryWomenFarmer: "महिला किसान",
    profitCalculatorTitle: "लाभ कैलकुलेटर",
    sellingPriceLabel: "बिक्री मूल्य (₹/क्विंटल)",
    sellingPricePlaceholder: "बिक्री मूल्य दर्ज करें (वैकल्पिक)",
    productionCostLabel: "कुल उत्पादन लागत (₹)",
    productionCostPlaceholder: "कुल उत्पादन लागत दर्ज करें",
    calculateProfitButton: "लाभ की गणना करें",
    totalRevenueLabel: "कुल राजस्व",
    totalCostLabel: "कुल लागत",
    netProfitLabel: "शुद्ध लाभ",
    profitStatus: "लाभ",
    lossStatus: "हानि",
    priceUsedLabel: "उपयोग किया गया मूल्य",
    usedMspLabel: "MSP उपयोग किया गया",
    usedCustomPriceLabel: "कस्टम बिक्री मूल्य उपयोग किया गया",
    successBidPlaced: "बोली सफलतापूर्वक लगाई गई!",
    admin_statTotalUsers: "कुल उपयोगकर्ता",
    admin_statTotalListings: "कुल सूचीबद्धियाँ",
    admin_statTotalBids: "कुल बोलियाँ",
    admin_statOpenSold: "खुला / बिका",
    card_base: "मूल्य:",
    card_highestBid: "उच्चतम बोली:",
    card_yourBidPlaceholder: "आपकी बोली (₹)",
    card_bidButton: "बोली",
    registeredUsers: "पंजीकृत उपयोगकर्ता",
    nameHeader: "नाम",
    emailHeader: "ईमेल",
    roleHeader: "भूमिका",
    noUsersYet: "कोई उपयोगकर्ता अभी तक पंजीकृत नहीं।",
    allCropListings: "सभी फसल सूचीबद्धियाँ",
    byLabel: "द्वारा",
    listingRemoved: "सूची हटाई गई",
    removeBtn: "हटाएँ",
    adminAccessRequired: "प्रशासन पहुंच आवश्यक है।",
    bidsSuffix: "बोली",
    noListingsMessage: "आपने अभी तक कोई फसल सूचीबद्ध नहीं की है।",
    requiredDocumentsLabel: "आवश्यक दस्तावेज़",
    scheme_PMKISAN_doc1: "आधार कार्ड",
    scheme_PMKISAN_doc2: "भूमि अभिलेख",
    scheme_PMKISAN_doc3: "बैंक खाता",
    scheme_PMFasal_doc1: "आधार कार्ड",
    scheme_PMFasal_doc2: "भूमि अभिलेख",
    scheme_PMFasal_doc3: "बैंक खाता",
    scheme_SoilHealth_doc1: "आधार कार्ड",
    scheme_SoilHealth_doc2: "भूमि अभिलेख",
    scheme_SoilHealth_doc3: "बैंक खाता",
    scheme_KCC_doc1: "आधार कार्ड",
    scheme_KCC_doc2: "भूमि अभिलेख",
    scheme_KCC_doc3: "बैंक खाता",
    scheme_eNAM_doc1: "आधार कार्ड",
    scheme_eNAM_doc2: "भूमि अभिलेख",
    scheme_eNAM_doc3: "बैंक खाता",
    scheme_PMKrishi_doc1: "आधार कार्ड",
    scheme_PMKrishi_doc2: "भूमि अभिलेख",
    scheme_PMKrishi_doc3: "बैंक खाता",
    scheme_KUSUM_doc1: "आधार कार्ड",
    scheme_KUSUM_doc2: "भूमि अभिलेख",
    scheme_KUSUM_doc3: "बैंक खाता",
    scheme_AIF_doc1: "आधार कार्ड",
    scheme_AIF_doc2: "भूमि अभिलेख",
    scheme_AIF_doc3: "बैंक खाता",
    scheme_BEE_doc1: "आधार कार्ड",
    scheme_BEE_doc2: "भूमि अभिलेख",
    scheme_BEE_doc3: "बैंक खाता",
    selectCalculatorTitle: "कैलकुलेटर चुनें",
    selectCalculatorSubtitle: "एमएसपी, सब्सिडी और लाभ — स्मार्ट खेती के निर्णय",
    mspCardTitle: "एमएसपी कैलकुलेटर",
    mspCardDesc: "अपनी फसलों के लिए न्यूनतम समर्थन मूल्य की गणना करें और बाजार बोली से तुलना करें",
    tractorCardTitle: "ट्रैक्टर सब्सिडी",
    tractorCardDesc: "जानें कि ट्रैक्टर खरीद पर आपको कितनी सरकारी सब्सिडी मिल सकती है",
    profitCardTitle: "लाभ कैलकुलेटर",
    profitCardDesc: "फसल उपज, बिक्री मूल्य और लागत के आधार पर अपना कृषि लाभ निकालें",
    openCalculator: "कैलकुलेटर खोलें →",
    subsidyCardTitle: "ट्रैक्टर सब्सिडी",
    subsidyCardDesc: "जानें कि ट्रैक्टर खरीद पर आपको कितनी सरकारी सब्सिडी मिल सकती है",
    stayUpdated: "अपडेट रहें",
    newsletterText: "नवीनतम फसल कीमतें, योजनाएँ और समाचार सीधे अपने इनबॉक्स में पाएं!",
    enterEmailPlaceholder: "अपना ईमेल दर्ज करें",
    subscribe: "सब्सक्राइब करें",
    privacyPolicy: "गोपनीयता नीति",
    termsOfService: "सेवा की शर्तें",
    supportText: "सहायता",
    aboutSubtitle: "भारत का किसान-प्रथम डिजिटल मार्केटप्लेस।",
    missionTitle: "हमारा मिशन",
    missionText: "बिचौलियों को हटाकर किसानों को सीधे खरीदारों से जोड़ना।",
    visionTitle: "हमारा विज़न",
    visionText: "एक डिजिटल भारत जहाँ हर किसान को उचित मूल्य और पारदर्शी व्यापार मिले।",
    whyTitle: "किसान बंधु क्यों?",
    whyText: "पारदर्शी बोली प्रणाली, फसल सलाह, MSP कैलकुलेटर और सरकारी योजनाएँ — एक ही प्लेटफ़ॉर्म पर।",
    featuresTitle: "मुख्य विशेषताएँ",
    featuresSubtitle: "जानिए कैसे किसान बंधु किसानों और खरीदारों के लिए लाभकारी है।",
    featureTransparencyTitle: "पारदर्शिता",
    featureTransparencyDesc: "किसानों और खरीदारों के बीच सीधे लेन-देन। कोई छिपा शुल्क नहीं।",
    featureFairTradeTitle: "निष्पक्ष व्यापार",
    featureFairTradeDesc: "कृषि आपूर्ति श्रृंखला में मूल्य का उचित वितरण।",
    featureUserFriendlyTitle: "उपयोग में आसान",
    featureUserFriendlyDesc: "किसानों और खरीदारों के लिए सरल, तेज और भरोसेमंद।",
    featureTraceabilityTitle: "फसल ट्रेसबिलिटी",
    featureTraceabilityDesc: "पूरी आपूर्ति श्रृंखला में अपनी फसल को ट्रैक करें। जल्द आ रहा है!",
    servicesTitle: "हमारी सेवाएँ",
    servicesSubtitle: "किसानों और खरीदारों की हर जरूरत — एक ही शक्तिशाली प्लेटफ़ॉर्म पर।",
    serviceMarketplaceTitle: "फसल मार्केटप्लेस",
    serviceMarketplaceDesc: "अपनी फसल सूचीबद्ध करें और सर्वोत्तम बोलियाँ प्राप्त करें।",
    serviceAdvisoryTitle: "फसल सलाह",
    serviceAdvisoryDesc: "फसल चयन, कीट नियंत्रण और मौसम अलर्ट पर विशेषज्ञ सलाह।",
    serviceSchemesTitle: "सरकारी योजनाएँ",
    serviceSchemesDesc: "सरकारी योजनाओं, सब्सिडी और ऋण की जानकारी और आवेदन।",
    serviceMspTitle: "एमएसपी कैलकुलेटर",
    serviceMspDesc: "अपनी फसलों के लिए न्यूनतम समर्थन मूल्य तुरंत निकालें।",
    serviceSubsidyTitle: "सब्सिडी कैलकुलेटर",
    serviceSubsidyDesc: "उपलब्ध सरकारी सब्सिडी तुरंत निकालें।",
    serviceInsightsTitle: "मार्केट इनसाइट्स",
    serviceInsightsDesc: "रीयल-टाइम फसल मूल्य और बाजार रुझान।",
    learnMore: "और जानें",
    valueTitle: "हमारा मूल्य प्रस्ताव",
    valueSubtitle: "किसान बंधु किसानों को सीधे खरीदारों से जोड़ता है।",
    networkTitle: "भारत भर में हमारा नेटवर्क",
    networkSubtitle: "किसान और खरीदार पूरे देश में जुड़े हुए हैं।",
    farmerLabel: "किसान",
    buyerLabel: "खरीदार",
    marketInsightsTitle: "मार्केट इनसाइट्स",
    marketInsightsSubtitle: "लाइव मंडी दरें, मूल्य रुझान, राज्य-वार डेटा — सब एक जगह।",
    updatedText: "अपडेट: आज, 9:00 AM",
    panIndia: "संपूर्ण भारत डेटा",
    cropsTracked: "12 फसलें ट्रैक की गई",
    livePrices: "लाइव कीमतें",
    priceCharts: "मूल्य चार्ट",
    stateWise: "राज्य अनुसार",
    demandTrends: "मांग रुझान",
    weatherImpact: "मौसम प्रभाव",
    liveMandiRates: "लाइव मंडी दरें",
    demoData: "डेमो डेटा",
    highDemand: "उच्च मांग",
    mediumDemand: "मध्यम मांग",
    veryHighDemand: "बहुत अधिक मांग",
    stableDemand: "स्थिर मांग",
    Wheat: "गेहूं",
    "Rice (Basmati)": "चावल (बासमती)",
    Cotton: "कपास",
    Soybean: "सोयाबीन",
    Maize: "मक्का",
    Tomato: "टमाटर",
    Onion: "प्याज",
    Potato: "आलू",
    Sugarcane: "गन्ना",
    Turmeric: "हल्दी",
    Chilli: "मिर्च",
    Groundnut: "मूंगफली",
    cropWheat: "गेहूं",
    cropRiceBasmati: "चावल (बासमती)",
    cropCotton: "कपास",
    cropSoybean: "सोयाबीन",
    cropMaize: "मक्का",
    cropTomato: "टमाटर",
    cropOnion: "प्याज",
    cropPotato: "आलू",
    cropSugarcane: "गन्ना",
    cropTurmeric: "हल्दी",
    cropChilli: "मिर्च",
    cropGroundnut: "मूंगफली",
    priceTrendOctMar: "मूल्य रुझान (अक्टूबर–मार्च)",
    sixMonthPriceTrends: "6 महीने के मूल्य रुझान",
    selectCropPriceHistory: "मूल्य इतिहास देखने के लिए फसल चुनें",
    stateWiseCropPrices: "राज्यवार फसल मूल्य",
    topCrop: "मुख्य फसल",
    rising: "बढ़ रहा है",
    falling: "घट रहा है",
    demandSupplyTrends: "मांग और आपूर्ति रुझान",
    demandLabel: "मांग",
    supplyLabel: "आपूर्ति",
    weatherImpactCrops: "फसलों पर मौसम का प्रभाव",
    favorable: "अनुकूल",
    riskAlert: "जोखिम चेतावनी",
    monitor: "निगरानी करें",
    weeklyFarmingAdvisory: "साप्ताहिक कृषि सलाह",
    sowNow: "अभी बोएं",
    sowNowCrops: "टमाटर, प्याज, हरी सब्जियां",
    harvestReady: "कटाई के लिए तैयार",
    harvestReadyCrops: "गेहूं, सरसों, चना",
    avoidThisWeek: "इस सप्ताह बचें",
    avoidThisWeekCrops: "भारी बारिश वाले क्षेत्रों में कपास",
    northIndia: "उत्तर भारत",
    southIndia: "दक्षिण भारत",
    eastIndia: "पूर्व भारत",
    westIndia: "पश्चिम भारत",
    centralIndia: "मध्य भारत",
    clear: "साफ मौसम",
    heavyRain: "भारी बारिश",
    partlyCloudy: "आंशिक बादल",
    sunny: "धूप",
    intermittentRain: "रुक-रुक कर बारिश",
    wheatHarvestGood: "गेहूं की कटाई के लिए अच्छा",
    cottonRisk: "कपास और मिर्च के लिए जोखिम",
    riceModerate: "चावल के लिए मध्यम स्थिति",
    groundnutGood: "मूंगफली के लिए अच्छा",
    soybeanWatch: "सोयाबीन की नमी पर ध्यान दें",
    statePunjab: "पंजाब",
    stateUttarPradesh: "उत्तर प्रदेश",
    stateMaharashtra: "महाराष्ट्र",
    stateMadhyaPradesh: "मध्य प्रदेश",
    stateAndhraPradesh: "आंध्र प्रदेश",
    stateKarnataka: "कर्नाटक",
    stateGujarat: "गुजरात",
    stateWestBengal: "पश्चिम बंगाल",
    backToCalculators: "कैलकुलेटर पर वापस जाएं",
    tractorSubsidySubtitle: "ट्रैक्टर खरीद पर सरकारी सब्सिडी की गणना करें",
    profitCalculatorSubtitle: "अपनी खेती का शुद्ध लाभ ज्ञात करें",
    quantityQuintalsLabel: "मात्रा (क्विंटल)",
    profitResultTitle: "आपका लाभ परिणाम",
    mspPriceUsedLabel: "एमएसपी मूल्य उपयोग किया गया",
    revenueLabel: "राजस्व",
    costLabel: "लागत",
    lossLabel: "हानि",
    calculateProfit: "लाभ की गणना करें",
    region_North_East: "उत्तर-पूर्व",
    marketInsights: "मार्केट इनसाइट्स",
    joinNow: "अभी जुड़ें",
    statesCovered: "कवर किए गए राज्य",
    farmersCount: "किसान",
    buyersCount: "खरीदार",
    marketBidLabel: "मार्केट बोली",
    noBids: "कोई बोली नहीं",
    basedOnMarketplace: "मार्केटप्लेस के आधार पर",
    subsidyResultTitle: "सब्सिडी परिणाम",
    subsidySavedMessage: "आपने ₹{amount} की बचत की",
    marketplaceSubtitle: "भारत भर के किसानों से ताज़ी फसलों पर सीधे बोली लगाएँ",
    totalListings: "कुल लिस्टिंग",
    openForBids: "बोली के लिए खुला",
    totalBids: "कुल बोलियाँ",
    searchCropsPlaceholder: "फसलें खोजें...",
    latest: "नवीनतम",
    priceLowHigh: "कम से ज्यादा कीमत",
    priceHighLow: "ज्यादा से कम कीमत",
    byQuantity: "मात्रा के अनुसार",
    allCrops: "सभी फसलें",
    grains: "अनाज",
    vegetables: "सब्जियां",
    fruits: "फल",
    cashCrops: "नकदी फसलें",
    pulses: "दालें",
    showingListings: "{count} लिस्टिंग दिखाई जा रही हैं",
    sortedBy: "क्रमबद्ध:",
    noListingsAvailable: "अभी कोई लिस्टिंग उपलब्ध नहीं है",
    listCropsMessage: "अपनी फसलें डैशबोर्ड से जोड़ें!",
    "price-low": "कम से ज्यादा कीमत",
    "price-high": "ज्यादा से कम कीमत",
    quantity: "मात्रा के अनुसार",
    yield: "उपज",
    profit: "लाभ",
    water: "पानी",
  },
} as const;

type TranslationKeys = keyof typeof translations.en;

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<Lang>("en");

  const t = (key: string): string => {
    const value = (translations[lang] as Record<string, string>)[key];
    return value || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
};
