import React, { createContext, useContext, useState, ReactNode } from "react";

// supported languages
export type Lang = "en" | "hi";

const translations = {
  en: {
    home: "Home",
    marketplace: "Marketplace",
    cropAdvisory: "Crop Advisory",
    mspCalculator: "Calculator",
    govSchemes: "Gov Schemes",
    myDashboard: "My Dashboard",
    adminPanel: "Admin Panel",
    loginSignup: "Login / Sign Up",
    logout: "Logout",
    heroTitle: "Kisan Bandhu",
    heroSubtitle: "Empowering Farmers. Connecting Markets.",
    exploreMarketplace: "Explore Marketplace",
    aboutTitle: "About Kisan Bandhu",
    aboutDescription:
      "Kisan Bandhu is India's farmer-first digital marketplace that eliminates middlemen and connects farmers directly with buyers. Our platform ensures fair prices through a transparent bidding system, provides crop advisory services, and helps farmers access government schemes — all in one place.",
    howItWorks: "How It Works",
    readyToGetStarted: "Ready to Get Started?",
    ctaDescription:
      "Join thousands of farmers and buyers on India's most trusted agricultural marketplace.",
    joinKisanBandhu: "Join Kisan Bandhu",
    marketplaceTitle: " Marketplace",
    marketplaceDescription: "Browse and bid on crops from farmers across India",
    pleaseLoginBid: "Please login to place a bid",
    bidSuccess: "Bid placed successfully!",
    onlyBuyer: "Only buyers can place bids.",
    searchPlaceholder: "Search crops...",
    sortLatest: "Latest",
    sortPriceLow: "Price: Low → High",
    sortPriceHigh: "Price: High → Low",
    sortQuantity: "Quantity",
    noCropsFound: "No crops found matching your criteria.",
    welcomeBack: "Welcome Back!",
    createAccountHeader: "Create Account",
    loginPrompt: "Login to your Kisan Bandhu account",
    joinPrompt: "Join Kisan Bandhu today",
    fullNameLabel: "Full Name",
    enterFullName: "Enter your full name",
    emailLabel: "Email",
    enterYourEmail: "Enter your email",
    passwordLabel: "Password",
    enterYourPassword: "Enter your password",
    roleLabel: "I am a",
    farmerRole: "Farmer",
    buyerRole: "Buyer",
    loginButton: "Login",
    createAccountButton: "Create Account",
    dontHaveAccount: "Don't have an account? Sign Up",
    alreadyHaveAccount: "Already have an account? Login",
    errorEmailPassword: "Email and password are required.",
    errorNameRequired: "Name is required.",
    errorPasswordLength: "Password must be at least 6 characters.",
    errorInvalidEmail: "Enter a valid email address.",
    errorInvalidCredentials: "Invalid email or password.",
    errorAccountExists: "Account already exists with this email.",
    governmentSchemesTitle: "🏛️ Government Schemes",
    governmentSchemesDescription: "Important farmer welfare schemes by the Government of India",
    eligibilityLabel: "Eligibility:",
    benefitsLabel: "Benefits:",
    requiredDocuments: "Required Documents",
    docAadhaar: "Aadhaar Card",
    docLand: "Land Record",
    docBank: "Bank Account",
    applyNow: "Apply Now →",
    mspCalculatorTitle: "🧮 Smart Farming Calculator",
    mspSectionTitle: "MSP Calculator",
    mspCalculatorDescription: "Calculate Minimum Support Price value for your harvest",
    selectCropLabel: "Select Crop",
    chooseCropPlaceholder: "Choose a crop",
    quantityLabel: "Quantity (quintals)",
    quantityPlaceholder: "e.g. 50",
    calculateMspButton: "Calculate MSP Value",
    mspResultTitle: "Your MSP Result",
    mspValueLabel: "MSP Value",
    marketBidValueLabel: "Market Bid Value",
    basedOnMarket: "Based on current marketplace",
    marketAbove: "✅ Market bid is ₹{diff} above MSP!",
    marketBelow: "⚠️ Market bid is ₹{diff} below MSP. Consider MSP route.",
    noBidsYet: "No bids yet",
    cropAdvisoryTitle: "🌱 Crop Advisory",
    cropAdvisoryDescription: "Get personalized crop recommendations based on your conditions",
    soilTypeLabel: "Soil Type",
    seasonLabel: "Season",
    regionLabel: "Region",
    selectSoilPlaceholder: "Select Soil",
    selectSeasonPlaceholder: "Select Season",
    selectRegionPlaceholder: "Select Region",
    getRecommendations: "Get Recommendations",
    yieldLabel: "Yield:",
    profitLabel: "Profit:",
    waterLabel: "Water:",
    water_High: "High",
    water_Medium: "Medium",
    water_Low: "Low",
    unit_quintalsPerHectare: "quintals/hectare",
    chooseOption: "Choose an option",
    brandName: "Kisan Bandhu",
    brandDescription: "Empowering farmers by connecting them directly to buyers. Fair prices, transparent bidding, better lives.",
    quickLinks: "Quick Links",
    contactUs: "Contact Us",
    followUs: "Follow Us",
    soil_Alluvial: "Alluvial",
    soil_Black_Regur: "Black (Regur)",
    soil_BlackRegur: "Black (Regur)",
    soil_Red: "Red",
    soil_Laterite: "Laterite",
    soil_Sandy: "Sandy",
    soil_Clay: "Clay",
    season_Kharif: "Kharif (Monsoon)",
    season_Rabi: "Rabi (Winter)",
    season_Zaid: "Zaid (Summer)",
    region_North: "North",
    region_South: "South",
    region_East: "East",
    region_West: "West",
    region_Central: "Central",
    region_NorthEast: "North-East",
    crop_Wheat: "Wheat",
    crop_Rice: "Rice",
    crop_Maize: "Maize",
    crop_Cotton: "Cotton",
    crop_Sugarcane: "Sugarcane",
    crop_Mustard: "Mustard",
    crop_Chickpea_Chana: "Chickpea (Chana)",
    crop_Soybean: "Soybean",
    crop_MoongDal: "Moong Dal",
    crop_Jowar: "Jowar",
    crop_Bajra: "Bajra",
    crop_Groundnut: "Groundnut",
    scheme_PMKISAN_name: "PM-KISAN",
    scheme_PMKISAN_desc: "Direct income support of ₹6,000 per year to farmer families in three equal installments.",
    scheme_PMKISAN_eligibility: "All land-holding farmer families with cultivable land.",
    scheme_PMKISAN_benefits: "₹6,000/year direct bank transfer, no middlemen involved.",
    scheme_PMFasal_name: "PM Fasal Bima Yojana",
    scheme_PMFasal_desc: "Crop insurance scheme providing financial support against crop loss due to natural calamities.",
    scheme_PMFasal_eligibility: "All farmers growing notified crops in notified areas.",
    scheme_PMFasal_benefits: "Low premium rates: 2% for Kharif, 1.5% for Rabi, 5% for commercial crops.",
    scheme_SoilHealth_name: "Soil Health Card Scheme",
    scheme_SoilHealth_desc: "Provides soil health cards with crop-wise nutrient recommendations to farmers.",
    scheme_SoilHealth_eligibility: "All farmers across India.",
    scheme_SoilHealth_benefits: "Free soil testing, personalized fertilizer recommendations, improved yield.",
    scheme_KCC_name: "Kisan Credit Card (KCC)",
    scheme_KCC_desc: "Provides affordable credit to farmers for cultivation, post-harvest, and consumption needs.",
    scheme_KCC_eligibility: "Farmers, fishermen, and animal husbandry farmers.",
    scheme_KCC_benefits: "Credit up to ₹3 lakh at 4% interest, crop insurance coverage included.",
    scheme_eNAM_name: "e-NAM (National Agriculture Market)",
    scheme_eNAM_desc: "Online trading platform for agricultural commodities to ensure better prices for farmers.",
    scheme_eNAM_eligibility: "Registered farmers and traders.",
    scheme_eNAM_benefits: "Transparent price discovery, reduced middlemen, wider market access.",
    scheme_PMKrishi_name: "PM Krishi Sinchai Yojana",
    scheme_PMKrishi_desc: "Ensures access to water for irrigation with 'Har Khet Ko Pani' initiative.",
    scheme_PMKrishi_eligibility: "All farmers with focus on water-scarce areas.",
    scheme_PMKrishi_benefits: "Subsidized micro-irrigation, drip irrigation systems, water harvesting support.",
    scheme_KUSUM_name: "PM KUSUM Yojana",
    scheme_KUSUM_desc: "Supports farmers to install solar pumps and generate additional income.",
    scheme_KUSUM_eligibility: "All farmers interested in solar pump installation.",
    scheme_KUSUM_benefits: "Subsidy on solar pumps, reduced diesel cost, and extra income through solar energy.",
    scheme_AIF_name: "Agriculture Infrastructure Fund",
    scheme_AIF_desc: "Provides financing for warehouses, cold storage, and post-harvest management infrastructure.",
    scheme_AIF_eligibility: "Farmers, FPOs, agri-entrepreneurs, startups, and cooperatives.",
    scheme_AIF_benefits: "Affordable loans, interest subvention, and support for agriculture infrastructure development.",
    scheme_BEE_name: "National Beekeeping & Honey Mission",
    scheme_BEE_desc: "Promotes beekeeping and honey production for additional farmer income.",
    scheme_BEE_eligibility: "Farmers, beekeepers, and interested rural entrepreneurs.",
    scheme_BEE_benefits: "Support for beekeeping equipment, training, and honey production income.",
    farmerDashboardTitle: "🧑‍🌾 Farmer Dashboard",
    buyerDashboardTitle: "🛒 Buyer Dashboard",
    adminPortalTitle: "⚙️ Admin Portal",
    adminPortalDesc: "Platform overview and management",
    welcomeUser: "Welcome, {name}",
    addCrop: "Add Crop",
    listNewCrop: "List a New Crop",
    cropNameLabel: "Crop Name",
    cropNamePlaceholder: "e.g. Wheat",
    cropTypeLabel: "Crop Type",
    cropType_grain: "Grain",
    cropType_vegetable: "Vegetable",
    cropType_fruit: "Fruit",
    cropType_cash_crop: "Cash Crop",
    cropType_pulse: "Pulse",
    market_crop_all: "All Crops",
    market_crop_grain: "🌾 Grains",
    market_crop_vegetable: "🥬 Vegetables",
    market_crop_fruit: "🍎 Fruits",
    market_crop_cash_crop: "🌿 Cash Crops",
    market_crop_pulse: "🫘 Pulses",
    basePriceLabel: "Base Price (₹/quintal)",
    basePricePlaceholder: "e.g. 2200",
    listCropButton: "List Crop",
    cancel: "Cancel",
    status_Open: "Open",
    status_Sold: "Sold",
    viewBids: "Bids",
    acceptBest: "Accept Best",
    errorFillAllFields: "Fill all fields.",
    successCropListed: "Crop listed successfully!",
    successBidAccepted: "Bid accepted! Crop marked as sold.",
    myBidHistory: "My Bid History",
    myBestBidLabel: "My best bid:",
    highestLabel: "Highest:",
    wonStatus: "Won! 🎉",
    lostStatus: "Lost",
    availableCrops: "Available Crops",
    tractorSubsidyTitle: "Tractor Subsidy Calculator",
    tractorPriceLabel: "Tractor Price (₹)",
    enterTractorPrice: "Enter tractor price",
    farmerCategoryLabel: "Farmer Category",
    selectCategory: "Select Category",
    calculateSubsidy: "Calculate Subsidy",
    governmentSubsidy: "Government Subsidy",
    finalPriceAfterSubsidy: "Final Price After Subsidy",
    categoryGeneralFarmer: "General Farmer",
    categorySCSTFarmer: "SC/ST Farmer",
    categoryWomenFarmer: "Women Farmer",
    profitCalculatorTitle: "Profit Calculator",
    sellingPriceLabel: "Selling Price (₹/quintal)",
    sellingPricePlaceholder: "Enter selling price (optional, MSP will be used if empty)",
    productionCostLabel: "Total Production Cost (₹)",
    productionCostPlaceholder: "Enter total production cost",
    calculateProfitButton: "Calculate Profit",
    totalRevenueLabel: "Total Revenue",
    totalCostLabel: "Total Cost",
    netProfitLabel: "Net Profit",
    profitStatus: "Profit",
    lossStatus: "Loss",
    priceUsedLabel: "Price Used",
    usedMspLabel: "MSP Used",
    usedCustomPriceLabel: "Custom Selling Price Used",
    card_base: "Base price:",
    card_highestBid: "Highest bid:",
    card_yourBidPlaceholder: "Your bid (₹)",
    card_bidButton: "Bid",
    successBidPlaced: "Bid placed successfully!",
    admin_statTotalUsers: "Total Users",
    admin_statTotalListings: "Total Listings",
    admin_statTotalBids: "Total Bids",
    admin_statOpenSold: "Open / Sold",
    registeredUsers: "Registered Users",
    nameHeader: "Name",
    emailHeader: "Email",
    roleHeader: "Role",
    noUsersYet: "No users registered yet.",
    allCropListings: "All Crop Listings",
    byLabel: "by",
    listingRemoved: "Listing removed",
    removeBtn: "Remove",
    adminAccessRequired: "Admin access required.",
    bidsSuffix: "bid(s)",
    noListingsMessage: "You haven't listed any crops yet. Click \"Add Crop\" to get started!",
    requiredDocumentsLabel: "Required Documents",
    scheme_PMKISAN_doc1: "Aadhaar Card",
scheme_PMKISAN_doc2: "Land Record",
scheme_PMKISAN_doc3: "Bank Account",
    scheme_PMFasal_doc1: "Aadhaar Card",
scheme_PMFasal_doc2: "Land Record",
scheme_PMFasal_doc3: "Bank Account",

scheme_SoilHealth_doc1: "Aadhaar Card",
scheme_SoilHealth_doc2: "Land Record",
scheme_SoilHealth_doc3: "Bank Account",

scheme_KCC_doc1: "Aadhaar Card",
scheme_KCC_doc2: "Land Record",
scheme_KCC_doc3: "Bank Account",

scheme_eNAM_doc1: "Aadhaar Card",
scheme_eNAM_doc2: "Land Record",
scheme_eNAM_doc3: "Bank Account",

scheme_PMKrishi_doc1: "Aadhaar Card",
scheme_PMKrishi_doc2: "Land Record",
scheme_PMKrishi_doc3: "Bank Account",

scheme_KUSUM_doc1: "Aadhaar Card",
scheme_KUSUM_doc2: "Land Record",
scheme_KUSUM_doc3: "Bank Account",

scheme_AIF_doc1: "Aadhaar Card",
scheme_AIF_doc2: "Land Record",
scheme_AIF_doc3: "Bank Account",

scheme_BEE_doc1: "Aadhaar Card",
scheme_BEE_doc2: "Land Record",
scheme_BEE_doc3: "Bank Account",
selectCalculatorTitle: "SELECT A CALCULATOR",
selectCalculatorSubtitle: "MSP, Subsidy & Profit — smart farming decisions",

mspCardTitle: "MSP CALCULATOR",
mspCardDesc: "Calculate Minimum Support Price for your crops and compare with market bids",

tractorCardTitle: "TRACTOR SUBSIDY",
tractorCardDesc: "Find out how much government subsidy you can get on tractor purchase",

profitCardTitle: "PROFIT CALCULATOR",
profitCardDesc: "Calculate your farming profit based on crop yield, selling price and costs",

openCalculator: "Open Calculator →",
subsidyCardTitle: "Tractor Subsidy",
subsidyCardDesc: "Find out how much government subsidy you can get on tractor purchase",
stayUpdated: "Stay Updated",
newsletterText: "Get latest crop prices, schemes & news directly in your inbox!",
enterEmailPlaceholder: "Enter your email",
subscribe: "Subscribe",
privacyPolicy: "Privacy Policy",
termsOfService: "Terms of Service",
supportText: "Support",

aboutSubtitle: "India's farmer-first digital marketplace — eliminating middlemen, ensuring fair prices, and empowering every kisan.",

missionTitle: "Our Mission",
missionText: "To eliminate middlemen and give farmers direct access to buyers — ensuring maximum profit stays with the farmer.",

visionTitle: "Our Vision",
visionText: "A digital India where every farmer gets a fair price, transparent trade, and access to government schemes — all in one place.",

whyTitle: "Why Kisan Bandhu?",
whyText: "Transparent bidding, crop advisory, MSP calculator, and government schemes — everything a farmer needs, in one platform.",
featuresTitle: "Key Features",
featuresSubtitle: "Discover how Kisan Bandhu can benefit farmers, buyers and all agricultural supply chain actors.",

featureTransparencyTitle: "Transparency",
featureTransparencyDesc: "Direct transactions between farmers and buyers. No hidden charges, no middlemen.",

featureFairTradeTitle: "Fair Trade",
featureFairTradeDesc: "Redistribution of value in the agricultural supply chain. Fair prices for all.",

featureUserFriendlyTitle: "User Friendly",
featureUserFriendlyDesc: "Easy to use platform for farmers and buyers. Simple, fast and reliable.",

featureTraceabilityTitle: "Crop Traceability",
featureTraceabilityDesc: "Track your crop through the entire supply chain. Coming soon!",
servicesTitle: "Our Services",
servicesSubtitle: "Everything a farmer and buyer needs — in one powerful platform.",

serviceMarketplaceTitle: "Crop Marketplace",
serviceMarketplaceDesc: "List your crops and get the best bids from verified buyers across India. No middlemen, maximum profit.",

serviceAdvisoryTitle: "Crop Advisory",
serviceAdvisoryDesc: "Get expert advice on crop selection, pest control, weather alerts and best farming practices.",

serviceSchemesTitle: "Gov Schemes",
serviceSchemesDesc: "Discover and apply for government schemes, subsidies and loans designed for Indian farmers.",

serviceMspTitle: "MSP Calculator",
serviceMspDesc: "Calculate Minimum Support Price for your crops instantly. Know your rights, get fair value.",

serviceSubsidyTitle: "Subsidy Calculator",
serviceSubsidyDesc: "Calculate government subsidies available for your crops, equipment and farming inputs instantly.",

serviceInsightsTitle: "Market Insights",
serviceInsightsDesc: "Real-time crop prices, market trends and demand forecasts to help you make smarter decisions.",

learnMore: "Learn More",
valueTitle: "Our Value Proposition",
valueSubtitle: "Kisan Bandhu connects farmers directly with buyers — eliminating middlemen, ensuring fair prices and transparent trade.",

networkTitle: "Our Network Across India",
networkSubtitle: "Farmers and buyers connected across the country — from Kashmir to Kanyakumari.",

farmerLabel: "Farmer",
buyerLabel: "Buyer",
marketInsightsTitle: "Market Insights",
marketInsightsSubtitle: "Live mandi rates, price trends, state-wise data & weather impact — all in one place.",

updatedText: "Updated: Today, 9:00 AM",
panIndia: "Pan India Data",
cropsTracked: "12 Crops Tracked",

livePrices: "Live Prices",
priceCharts: "Price Charts",
stateWise: "State Wise",
demandTrends: "Demand Trends",
weatherImpact: "Weather Impact",

liveMandiRates: "Live Mandi Rates",
demoData: "Demo Data",

highDemand: "High Demand",
mediumDemand: "Medium Demand",
veryHighDemand: "Very High Demand",
stableDemand: "Stable Demand",
Wheat: "Wheat",
"Rice (Basmati)": "Rice (Basmati)",
Cotton: "Cotton",
Soybean: "Soybean",
Maize: "Maize",
Tomato: "Tomato",
Onion: "Onion",
Potato: "Potato",
Sugarcane: "Sugarcane",
Turmeric: "Turmeric",
Chilli: "Chilli",
Groundnut: "Groundnut",
cropWheat: "Wheat",
cropRiceBasmati: "Rice (Basmati)",
cropCotton: "Cotton",
cropSoybean: "Soybean",
cropMaize: "Maize",
cropTomato: "Tomato",
cropOnion: "Onion",
cropPotato: "Potato",
cropSugarcane: "Sugarcane",
cropTurmeric: "Turmeric",
cropChilli: "Chilli",
cropGroundnut: "Groundnut",
priceTrendOctMar: "Price Trend (Oct–Mar)",
sixMonthPriceTrends: "6-Month Price Trends",
selectCropPriceHistory: "Select a crop to view its price history",
stateWiseCropPrices: "State Wise Crop Prices",
topCrop: "Top Crop",
rising: "Rising",
falling: "Falling",
demandSupplyTrends: "Demand & Supply Trends",
demandLabel: "Demand",
supplyLabel: "Supply",
weatherImpactCrops: "Weather Impact on Crops",
favorable: "Favorable",
riskAlert: "Risk Alert",
monitor: "Monitor",
weeklyFarmingAdvisory: "Weekly Farming Advisory",
sowNow: "Sow Now",
sowNowCrops: "Tomato, Onion, Green Vegetables",
harvestReady: "Harvest Ready",
harvestReadyCrops: "Wheat, Mustard, Gram",
avoidThisWeek: "Avoid This Week",
avoidThisWeekCrops: "Cotton in heavy rain regions",
northIndia: "North India",
southIndia: "South India",
eastIndia: "East India",
westIndia: "West India",
centralIndia: "Central India",

clear: "Clear",
heavyRain: "Heavy Rain",
partlyCloudy: "Partly Cloudy",
sunny: "Sunny",
intermittentRain: "Intermittent Rain",

wheatHarvestGood: "Good for Wheat harvest",
cottonRisk: "Risk for Cotton & Chilli",
riceModerate: "Moderate for Rice",
groundnutGood: "Good for Groundnut",
soybeanWatch: "Watch Soybean moisture",
statePunjab: "Punjab",
stateUttarPradesh: "Uttar Pradesh",
stateMaharashtra: "Maharashtra",
stateMadhyaPradesh: "Madhya Pradesh",
stateAndhraPradesh: "Andhra Pradesh",
stateKarnataka: "Karnataka",
stateGujarat: "Gujarat",
stateWestBengal: "West Bengal",
backToCalculators: "Back to Calculators",
tractorSubsidySubtitle: "Calculate government subsidy on tractor purchase",
profitCalculatorSubtitle: "Calculate your net farming profit",
quantityQuintalsLabel: "Quantity (quintals)",
profitResultTitle: "Your Profit Result",
mspPriceUsedLabel: "MSP price used",
revenueLabel: "Revenue",
costLabel: "Cost",
lossLabel: "Loss",
calculateProfit: "Calculate Profit",
region_North_East: "North-East",
  marketInsights: "Market Insights",
  joinNow: "Join Now",
  statesCovered: "States Covered",
farmersCount: "Farmers",
buyersCount: "Buyers",
marketBidLabel: "Market Bid",
noBids: "No Bids",
basedOnMarketplace: "Based on Marketplace",
subsidyResultTitle: "Subsidy Result",
subsidySavedMessage: "You saved ₹{amount}",
marketplaceSubtitle: "Browse and bid on fresh crops directly from farmers across India",
totalListings: "Total Listings",
openForBids: "Open for Bids",
totalBids: "Total Bids",
searchCropsPlaceholder: "Search crops...",
latest: "Latest",
priceLowHigh: "Price: Low to High",
priceHighLow: "Price: High to Low",
byQuantity: "By Quantity",
allCrops: "All Crops",
grains: "Grains",
vegetables: "Vegetables",
fruits: "Fruits",
cashCrops: "Cash Crops",
pulses: "Pulses",
showingListings: "Showing {count} listings",
sortedBy: "Sorted by:",
noListingsAvailable: "No listings available right now",
listCropsMessage: "List your crops from your dashboard!",
"price-low": "Price: Low to High",
"price-high": "Price: High to Low",
quantity: "By Quantity",


  },
  hi: {
    home: "होम",
    marketplace: "मार्केटप्लेस",
    cropAdvisory: "फसल सलाह",
    mspCalculator: "कैलकुलेटर",
    subsidyCalculator: "सब्सिडी कैल्क्युलेटर",
    govSchemes: "सरकारी योजनाएँ",
    myDashboard: "मेरा डैशबोर्ड",
    adminPanel: "प्रशासन पैनल",
    loginSignup: "लॉगिन / साइन अप",
    logout: "लॉगआउट",
    heroTitle: "किसान बंधु",
    heroSubtitle: "आपकी फ़सलें। आपकी क़ीमत। आपकी ताक़त।",
    exploreMarketplace: "मार्केटप्लेस देखें",
    aboutTitle: "किसान बंधु के बारे में",
    aboutDescription:
      "किसान बंधु भारत का किसान-प्रथम डिजिटल मार्केटप्लेस है जो दलालों को हटाकर किसानों को सीधे खरीदारों से जोड़ता है। हमारी प्लेटफ़ॉर्म पारदर्शी बोली प्रणाली के माध्यम से उचित मूल्य सुनिश्चित करती है, फसल सलाह सेवाएँ प्रदान करती है, और किसानों को सरकारी योजनाओं तक पहुँचने में मदद करती है — एक ही स्थान पर।",
    howItWorks: "यह कैसे काम करता है",
    readyToGetStarted: "शुरू करने के लिए तैयार?",
    ctaDescription:
      "भारत के सबसे विश्वसनीय कृषि बाजार पर हजारों किसानों और खरीदारों से जुड़ें।",
    joinKisanBandhu: "किसान बंधु में शामिल हों",
    marketplaceTitle: " मार्केटप्लेस",
    marketplaceDescription: "भारत भर के किसानों से फसलों पर नीलामी करें और बोली लगाएं",
    pleaseLoginBid: "बोली लगाने के लिए कृपया लॉगिन करें",
    bidSuccess: "बोली सफलतापूर्वक लगाई गई!",
    onlyBuyer: "केवल खरीदार बोली लगा सकते हैं।",
    searchPlaceholder: "फसलों की खोज करें...",
    sortLatest: "नवीनतम",
    sortPriceLow: "कीमत: कम → अधिक",
    sortPriceHigh: "कीमत: अधिक → कम",
    sortQuantity: "मात्रा",
    noCropsFound: "आपकी शर्तों के अनुरूप कोई फसल नहीं मिली।",
    welcomeBack: "वापसी पर स्वागत है!",
    createAccountHeader: "खाता बनाएं",
    loginPrompt: "अपने किसान बंधु खाते में लॉगिन करें",
    joinPrompt: "आज किसान बंधु में शामिल हों",
    fullNameLabel: "पूरा नाम",
    enterFullName: "अपना पूरा नाम दर्ज करें",
    emailLabel: "ईमेल",
    enterYourEmail: "अपना ईमेल दर्ज करें",
    passwordLabel: "पासवर्ड",
    enterYourPassword: "अपना पासवर्ड दर्ज करें",
    roleLabel: "मैं एक हूँ",
    farmerRole: "किसान",
    buyerRole: "खरीदार",
    loginButton: "लॉगिन",
    createAccountButton: "खाता बनाएं",
    dontHaveAccount: "खाता नहीं है? साइन अप करें",
    alreadyHaveAccount: "पहले से एक खाता है? लॉगिन करें",
    errorEmailPassword: "ईमेल और पासवर्ड आवश्यक हैं।",
    errorNameRequired: "नाम आवश्यक है।",
    errorPasswordLength: "पासवर्ड कम से कम 6 अक्षरों का होना चाहिए।",
    errorInvalidEmail: "एक वैध ईमेल पता दर्ज करें।",
    errorInvalidCredentials: "अमान्य ईमेल या पासवर्ड।",
    errorAccountExists: "इस ईमेल के साथ पहले से एक खाता मौजूद है।",
    governmentSchemesTitle: "🏛️ सरकारी योजनाएँ",
    governmentSchemesDescription: "भारत सरकार द्वारा महत्वपूर्ण किसान कल्याण योजनाएँ",
    eligibilityLabel: "योग्यता:",
    benefitsLabel: "लाभ:",
    requiredDocuments: "आवश्यक दस्तावेज",
    docAadhaar: "आधार कार्ड",
    docLand: "भूमि अभिलेख",
    docBank: "बैंक खाता",
    applyNow: "अब आवेदन करें →",
    mspCalculatorTitle: "🧮 स्मार्ट फार्मिंग कैलकुलेटर",
    mspSectionTitle: "एमएसपी कैलकुलेटर",
    mspCalculatorDescription: "अपने फसल के लिए न्यूनतम समर्थन मूल्य की गणना करें",
    selectCropLabel: "फसल चुनें",
    chooseCropPlaceholder: "फसल चुनें",
    quantityLabel: "मात्रा (क्विंटल)",
    quantityPlaceholder: "जैसे 50",
    calculateMspButton: "एमएसपी मान की गणना करें",
    mspResultTitle: "आपका एमएसपी परिणाम",
    mspValueLabel: "एमएसपी मूल्य",
    marketBidValueLabel: "बाजार बोली मूल्य",
    basedOnMarket: "वर्तमान बाज़ार के आधार पर",
    marketAbove: "✅ बाजार बोली MSP से ₹{diff} ऊपर है!",
    marketBelow: "⚠️ बाजार बोली MSP से ₹{diff} नीचे है। MSP मार्ग पर विचार करें।",
    noBidsYet: "अभी तक कोई बोली नहीं",
    cropAdvisoryTitle: "🌱 फसल सलाह",
    cropAdvisoryDescription: "आपकी परिस्थितियों के आधार पर व्यक्तिगत रूप से फसल की सिफारिशें प्राप्त करें",
    soilTypeLabel: "मिट्टी का प्रकार",
    seasonLabel: "मौसम",
    regionLabel: "क्षेत्र",
    selectSoilPlaceholder: "मिट्टी चुनें",
    selectSeasonPlaceholder: "मौसम चुनें",
    selectRegionPlaceholder: "क्षेत्र चुनें",
    getRecommendations: "अनुशंसाएँ प्राप्त करें",
    yieldLabel: "उपज:",
    profitLabel: "लाभ:",
    waterLabel: "पानी:",
    water_High: "उच्च",
    water_Medium: "मध्यम",
    water_Low: "निम्न",
    unit_quintalsPerHectare: "क्विंटल/हेक्टेयर",
    chooseOption: "एक विकल्प चुनें",
    brandName: "किसान बंधु",
    brandDescription: "किसानों को सीधे खरीदारों से जोड़कर उन्हें सशक्त बनाना। उचित मूल्य, पारदर्शी बोली, बेहतर जीवन।",
    quickLinks: "त्वरित लिंक",
    contactUs: "संपर्क करें",
    followUs: "हमें फॉलो करें",
    soil_Alluvial: "आलुवियल",
    soil_Black_Regur: "ब्लैक (रेगूर)",
    soil_BlackRegur: "ब्लैक (रेगूर)",
    soil_Red: "लाल",
    soil_Laterite: "लेटेराइट",
    soil_Sandy: "रेतीली",
    soil_Clay: "मिट्टी",
    season_Kharif: "खरीफ (मानसून)",
    season_Rabi: "रबी (सर्दी)",
    season_Zaid: "ज़ैद (गर्मी)",
    region_North: "उत्तर",
    region_South: "दक्षिण",
    region_East: "पूर्व",
    region_West: "पश्चिम",
    region_Central: "केंद्रीय",
    region_NorthEast: "उत्तर-पूर्व",
    crop_Wheat: "गेहूँ",
    crop_Rice: "चावल",
    crop_Maize: "मक्का",
    crop_Cotton: "कपास",
    crop_Sugarcane: "गन्ना",
    crop_Mustard: "सरसों",
    crop_Chickpea_Chana: "चना (काबुली)",
    crop_Soybean: "सोयाबीन",
    crop_MoongDal: "मूंग दाल",
    crop_Jowar: "ज्वार",
    crop_Bajra: "बाजरा",
    crop_Groundnut: "मूंगफली",
    scheme_PMKISAN_name: "पीएम-किसान",
    scheme_PMKISAN_desc: "किसान परिवारों को तीन समान किस्तों में प्रति वर्ष ₹6,000 की प्रत्यक्ष आय सहायता।",
    scheme_PMKISAN_eligibility: "खेती योग्य भूमि वाले सभी किसान परिवार।",
    scheme_PMKISAN_benefits: "₹6,000 प्रति वर्ष सीधे बैंक खाते में, बिना किसी दलाल के।",
    scheme_PMFasal_name: "प्रधानमंत्री फसल बीमा योजना",
    scheme_PMFasal_desc: "प्राकृतिक आपदाओं के कारण फसल नुकसान के खिलाफ वित्तीय सहायता प्रदान करने वाली फसल बीमा योजना।",
    scheme_PMFasal_eligibility: "अधिसूचित क्षेत्रों में अधिसूचित फसलें उगाने वाले सभी किसान।",
    scheme_PMFasal_benefits: "कम प्रीमियम दरें: खरीफ के लिए 2%, रबी के लिए 1.5%, वाणिज्यिक फसलों के लिए 5%।",
    scheme_SoilHealth_name: "मृदा स्वास्थ्य कार्ड योजना",
    scheme_SoilHealth_desc: "किसानों को फसल-वार पोषक तत्व सिफारिशों के साथ मृदा स्वास्थ्य कार्ड प्रदान करती है।",
    scheme_SoilHealth_eligibility: "भारत के सभी किसान।",
    scheme_SoilHealth_benefits: "मुफ्त मिट्टी परीक्षण, व्यक्तिगत उर्वरक सिफारिशें और बेहतर उपज।",
    scheme_KCC_name: "किसान क्रेडिट कार्ड (KCC)",
    scheme_KCC_desc: "खेती, फसल कटाई के बाद की जरूरतों और अन्य आवश्यकताओं के लिए सुलभ ऋण प्रदान करता है।",
    scheme_KCC_eligibility: "किसान, मछुआरे और पशुपालक किसान।",
    scheme_KCC_benefits: "₹3 लाख तक 4% ब्याज पर ऋण तथा फसल बीमा कवर।",
    scheme_eNAM_name: "ई-नाम (राष्ट्रीय कृषि बाजार)",
    scheme_eNAM_desc: "किसानों को बेहतर मूल्य दिलाने के लिए कृषि उपज का ऑनलाइन व्यापार मंच।",
    scheme_eNAM_eligibility: "पंजीकृत किसान और व्यापारी।",
    scheme_eNAM_benefits: "पारदर्शी मूल्य खोज, कम दलाल और व्यापक बाजार पहुंच।",
    scheme_PMKrishi_name: "प्रधानमंत्री कृषि सिंचाई योजना",
    scheme_PMKrishi_desc: "'हर खेत को पानी' पहल के तहत सिंचाई के लिए पानी की उपलब्धता सुनिश्चित करती है।",
    scheme_PMKrishi_eligibility: "विशेष रूप से जल-संकट क्षेत्रों सहित सभी किसान।",
    scheme_PMKrishi_benefits: "सब्सिडी वाली माइक्रो-सिंचाई, ड्रिप सिस्टम और जल संचयन सहायता।",
    scheme_KUSUM_name: "पीएम कुसुम योजना",
    scheme_KUSUM_desc: "किसानों को सोलर पंप लगाने और अतिरिक्त आय अर्जित करने में सहायता प्रदान करती है।",
    scheme_KUSUM_eligibility: "सोलर पंप स्थापना में रुचि रखने वाले सभी किसान।",
    scheme_KUSUM_benefits: "सोलर पंप पर सब्सिडी, डीजल खर्च में कमी और सौर ऊर्जा से अतिरिक्त आय।",
    scheme_AIF_name: "कृषि अवसंरचना निधि",
    scheme_AIF_desc: "वेयरहाउस, कोल्ड स्टोरेज और कटाई के बाद की कृषि अवसंरचना के लिए वित्तीय सहायता प्रदान करती है।",
    scheme_AIF_eligibility: "किसान, एफपीओ, कृषि उद्यमी, स्टार्टअप और सहकारी संस्थाएँ।",
    scheme_AIF_benefits: "सस्ती ऋण सुविधा, ब्याज में छूट और कृषि अवसंरचना विकास हेतु सहायता।",
    scheme_BEE_name: "राष्ट्रीय मधुमक्खी पालन एवं शहद मिशन",
    scheme_BEE_desc: "अतिरिक्त किसान आय के लिए मधुमक्खी पालन और शहद उत्पादन को बढ़ावा देता है।",
    scheme_BEE_eligibility: "किसान, मधुमक्खी पालक और इच्छुक ग्रामीण उद्यमी।",
    scheme_BEE_benefits: "मधुमक्खी पालन उपकरण, प्रशिक्षण और शहद उत्पादन से आय हेतु सहायता।",
    farmerDashboardTitle: "🧑‍🌾 किसान डैशबोर्ड",
    buyerDashboardTitle: "🛒 खरीदार डैशबोर्ड",
    adminPortalTitle: "⚙️ प्रशासन पोर्टल",
    adminPortalDesc: "प्लेटफ़ॉर्म अवलोकन और प्रबंधन",
    welcomeUser: "स्वागत है, {name}",
    addCrop: "फसल जोड़ें",
    listNewCrop: "नई फसल सूचीबद्ध करें",
    cropNameLabel: "फसल का नाम",
    cropNamePlaceholder: "जैसे गेहूँ",
    cropTypeLabel: "फसल का प्रकार",
    cropType_grain: "अनाज",
    cropType_vegetable: "सब्ज़ी",
    cropType_fruit: "फल",
    cropType_cash_crop: "नकदी फसल",
    cropType_pulse: "दाल",
    market_crop_all: "सभी फसलें",
    market_crop_grain: "🌾 अनाज",
    market_crop_vegetable: "🥬 सब्ज़ियाँ",
    market_crop_fruit: "🍎 फल",
    market_crop_cash_crop: "🌿 नकदी फसलें",
    market_crop_pulse: "🫘 दालें",
    basePriceLabel: "मूल्य (₹/क्विंटल)",
    basePricePlaceholder: "जैसे 2200",
    listCropButton: "फसल सूचीबद्ध करें",
    cancel: "रद्द करें",
    status_Open: "खुला",
    status_Sold: "बिक चुका",
    viewBids: "बोली",
    acceptBest: "सर्वोत्तम स्वीकार करें",
    errorFillAllFields: "सभी फ़ील्ड भरें।",
    successCropListed: "फसल सफलतापूर्वक सूचीबद्ध की गई!",
    successBidAccepted: "बोली स्वीकार की गई! फसल बेची हुई के रूप में चिह्नित।",
    myBidHistory: "मेरी बोली इतिहास",
    myBestBidLabel: "मेरी सर्वोत्तम बोली:",
    highestLabel: "सर्वोच्च:",
    wonStatus: "जीत गए! 🎉",
    lostStatus: "हार गए",
    availableCrops: "उपलब्ध फसलें",
    tractorSubsidyTitle: "ट्रैक्टर सब्सिडी कैलकुलेटर",
    tractorPriceLabel: "ट्रैक्टर की कीमत (₹)",
    enterTractorPrice: "ट्रैक्टर की कीमत दर्ज करें",
    farmerCategoryLabel: "किसान श्रेणी",
    selectCategory: "श्रेणी चुनें",
    calculateSubsidy: "सब्सिडी की गणना करें",
    governmentSubsidy: "सरकारी सब्सिडी",
    finalPriceAfterSubsidy: "सब्सिडी के बाद अंतिम कीमत",
    categoryGeneralFarmer: "सामान्य किसान",
    categorySCSTFarmer: "अनुसूचित जाति / अनुसूचित जनजाति किसान",
    categoryWomenFarmer: "महिला किसान",
    profitCalculatorTitle: "लाभ कैलकुलेटर",
    sellingPriceLabel: "बिक्री मूल्य (₹/क्विंटल)",
    sellingPricePlaceholder: "बिक्री मूल्य दर्ज करें (वैकल्पिक, खाली छोड़ने पर MSP उपयोग होगा)",
    productionCostLabel: "कुल उत्पादन लागत (₹)",
    productionCostPlaceholder: "कुल उत्पादन लागत दर्ज करें",
    calculateProfitButton: "लाभ की गणना करें",
    totalRevenueLabel: "कुल राजस्व",
    totalCostLabel: "कुल लागत",
    netProfitLabel: "शुद्ध लाभ",
    profitStatus: "लाभ",
    lossStatus: "हानि",
    priceUsedLabel: "उपयोग किया गया मूल्य",
    usedMspLabel: "MSP उपयोग किया गया",
    usedCustomPriceLabel: "कस्टम बिक्री मूल्य उपयोग किया गया",
    successBidPlaced: "बोली सफलतापूर्वक लगाई गई!",
    admin_statTotalUsers: "कुल उपयोगकर्ता",
    admin_statTotalListings: "कुल सूचीबद्धियाँ",
    admin_statTotalBids: "कुल बोलियाँ",
    admin_statOpenSold: "खुला / बिका",
    card_base: "मूल्य:",
    card_highestBid: "उच्चतम बोली:",
    card_yourBidPlaceholder: "आपकी बोली (₹)",
    card_bidButton: "बोली",
    registeredUsers: "पंजीकृत उपयोगकर्ता",
    nameHeader: "नाम",
    emailHeader: "ईमेल",
    roleHeader: "भूमिका",
    noUsersYet: "कोई उपयोगकर्ता अभी तक पंजीकृत नहीं।",
    allCropListings: "सभी फसल सूचीबद्धियाँ",
    byLabel: "द्वारा",
    listingRemoved: "सूची हटाई गई",
    removeBtn: "हटाएँ",
    adminAccessRequired: "प्रशासन पहुंच आवश्यक है।",
    bidsSuffix: "बोली",
    noListingsMessage: "आपने अभी तक कोई फसल सूचीबद्ध नहीं की है। शुरू करने के लिए \"फसल जोड़ें\" पर क्लिक करें!",
    requiredDocumentsLabel: "आवश्यक दस्तावेज़",
    scheme_PMKISAN_doc1: "आधार कार्ड",
scheme_PMKISAN_doc2: "भूमि अभिलेख",
scheme_PMKISAN_doc3: "बैंक खाता",
    scheme_PMFasal_doc1: "आधार कार्ड",
scheme_PMFasal_doc2: "भूमि अभिलेख",
scheme_PMFasal_doc3: "बैंक खाता",

scheme_SoilHealth_doc1: "आधार कार्ड",
scheme_SoilHealth_doc2: "भूमि अभिलेख",
scheme_SoilHealth_doc3: "बैंक खाता",

scheme_KCC_doc1: "आधार कार्ड",
scheme_KCC_doc2: "भूमि अभिलेख",
scheme_KCC_doc3: "बैंक खाता",

scheme_eNAM_doc1: "आधार कार्ड",
scheme_eNAM_doc2: "भूमि अभिलेख",
scheme_eNAM_doc3: "बैंक खाता",

scheme_PMKrishi_doc1: "आधार कार्ड",
scheme_PMKrishi_doc2: "भूमि अभिलेख",
scheme_PMKrishi_doc3: "बैंक खाता",

scheme_KUSUM_doc1: "आधार कार्ड",
scheme_KUSUM_doc2: "भूमि अभिलेख",
scheme_KUSUM_doc3: "बैंक खाता",

scheme_AIF_doc1: "आधार कार्ड",
scheme_AIF_doc2: "भूमि अभिलेख",
scheme_AIF_doc3: "बैंक खाता",

scheme_BEE_doc1: "आधार कार्ड",
scheme_BEE_doc2: "भूमि अभिलेख",
scheme_BEE_doc3: "बैंक खाता",

selectCalculatorTitle: "कैलकुलेटर चुनें",
selectCalculatorSubtitle: "एमएसपी, सब्सिडी और लाभ — स्मार्ट खेती के निर्णय",

mspCardTitle: "एमएसपी कैलकुलेटर",
mspCardDesc: "अपनी फसलों के लिए न्यूनतम समर्थन मूल्य की गणना करें और बाजार बोली से तुलना करें",

tractorCardTitle: "ट्रैक्टर सब्सिडी",
tractorCardDesc: "जानें कि ट्रैक्टर खरीद पर आपको कितनी सरकारी सब्सिडी मिल सकती है",

profitCardTitle: "लाभ कैलकुलेटर",
profitCardDesc: "फसल उपज, बिक्री मूल्य और लागत के आधार पर अपना कृषि लाभ निकालें",

openCalculator: "कैलकुलेटर खोलें →",
subsidyCardTitle: "ट्रैक्टर सब्सिडी",
subsidyCardDesc: "जानें कि ट्रैक्टर खरीद पर आपको कितनी सरकारी सब्सिडी मिल सकती है",
stayUpdated: "अपडेट रहें",
newsletterText: "नवीनतम फसल कीमतें, योजनाएँ और समाचार सीधे अपने इनबॉक्स में पाएं!",
enterEmailPlaceholder: "अपना ईमेल दर्ज करें",
subscribe: "सब्सक्राइब करें",
privacyPolicy: "गोपनीयता नीति",
termsOfService: "सेवा की शर्तें",
supportText: "सहायता",

aboutSubtitle: "भारत का किसान-प्रथम डिजिटल मार्केटप्लेस — बिचौलियों को हटाकर, उचित मूल्य सुनिश्चित करते हुए, हर किसान को सशक्त बनाना।",

missionTitle: "हमारा मिशन",
missionText: "बिचौलियों को हटाकर किसानों को सीधे खरीदारों से जोड़ना — ताकि अधिकतम लाभ किसान के पास ही रहे।",

visionTitle: "हमारा विज़न",
visionText: "एक डिजिटल भारत जहाँ हर किसान को उचित मूल्य, पारदर्शी व्यापार और सरकारी योजनाओं तक पहुँच मिले — सब कुछ एक ही प्लेटफ़ॉर्म पर।",

whyTitle: "किसान बंधु क्यों?",
whyText: "पारदर्शी बोली प्रणाली, फसल सलाह, MSP कैलकुलेटर और सरकारी योजनाएँ — एक ही प्लेटफ़ॉर्म पर किसानों की सभी जरूरतें।",
featuresTitle: "मुख्य विशेषताएँ",
featuresSubtitle: "जानिए कैसे किसान बंधु किसानों, खरीदारों और कृषि आपूर्ति श्रृंखला से जुड़े सभी लोगों के लिए लाभकारी है।",

featureTransparencyTitle: "पारदर्शिता",
featureTransparencyDesc: "किसानों और खरीदारों के बीच सीधे लेन-देन। कोई छिपा शुल्क नहीं, कोई बिचौलिया नहीं।",

featureFairTradeTitle: "निष्पक्ष व्यापार",
featureFairTradeDesc: "कृषि आपूर्ति श्रृंखला में मूल्य का उचित वितरण। सभी के लिए उचित कीमत।",

featureUserFriendlyTitle: "उपयोग में आसान",
featureUserFriendlyDesc: "किसानों और खरीदारों के लिए आसान प्लेटफ़ॉर्म। सरल, तेज और भरोसेमंद।",

featureTraceabilityTitle: "फसल ट्रेसबिलिटी",
featureTraceabilityDesc: "पूरी आपूर्ति श्रृंखला में अपनी फसल को ट्रैक करें। जल्द आ रहा है!",
servicesTitle: "हमारी सेवाएँ",
servicesSubtitle: "किसानों और खरीदारों की हर जरूरत — एक ही शक्तिशाली प्लेटफ़ॉर्म पर।",

serviceMarketplaceTitle: "फसल मार्केटप्लेस",
serviceMarketplaceDesc: "अपनी फसल सूचीबद्ध करें और पूरे भारत के सत्यापित खरीदारों से सर्वोत्तम बोलियाँ प्राप्त करें। कोई बिचौलिया नहीं, अधिकतम लाभ।",

serviceAdvisoryTitle: "फसल सलाह",
serviceAdvisoryDesc: "फसल चयन, कीट नियंत्रण, मौसम अलर्ट और सर्वोत्तम खेती पद्धतियों पर विशेषज्ञ सलाह प्राप्त करें।",

serviceSchemesTitle: "सरकारी योजनाएँ",
serviceSchemesDesc: "भारतीय किसानों के लिए बनाई गई सरकारी योजनाओं, सब्सिडी और ऋण की जानकारी प्राप्त करें और आवेदन करें।",

serviceMspTitle: "एमएसपी कैलकुलेटर",
serviceMspDesc: "अपनी फसलों के लिए न्यूनतम समर्थन मूल्य तुरंत निकालें। अपने अधिकार जानें, उचित मूल्य पाएं।",

serviceSubsidyTitle: "सब्सिडी कैलकुलेटर",
serviceSubsidyDesc: "अपनी फसलों, उपकरणों और कृषि इनपुट पर उपलब्ध सरकारी सब्सिडी तुरंत निकालें।",

serviceInsightsTitle: "मार्केट इनसाइट्स",
serviceInsightsDesc: "रीयल-टाइम फसल मूल्य, बाजार रुझान और मांग पूर्वानुमान जो आपको बेहतर निर्णय लेने में मदद करें।",

learnMore: "और जानें",
valueTitle: "हमारा मूल्य प्रस्ताव",
valueSubtitle: "किसान बंधु किसानों को सीधे खरीदारों से जोड़ता है — बिचौलियों को हटाकर, उचित मूल्य और पारदर्शी व्यापार सुनिश्चित करता है।",

networkTitle: "भारत भर में हमारा नेटवर्क",
networkSubtitle: "किसान और खरीदार पूरे देश में जुड़े हुए हैं — कश्मीर से कन्याकुमारी तक।",

farmerLabel: "किसान",
buyerLabel: "खरीदार",
marketInsightsTitle: "मार्केट इनसाइट्स",
marketInsightsSubtitle: "लाइव मंडी दरें, मूल्य रुझान, राज्य-वार डेटा और मौसम प्रभाव — सब कुछ एक ही स्थान पर।",

updatedText: "अपडेट: आज, 9:00 AM",
panIndia: "संपूर्ण भारत डेटा",
cropsTracked: "12 फसलें ट्रैक की गई",

livePrices: "लाइव कीमतें",
priceCharts: "मूल्य चार्ट",
stateWise: "राज्य अनुसार",
demandTrends: "मांग रुझान",
weatherImpact: "मौसम प्रभाव",

liveMandiRates: "लाइव मंडी दरें",
demoData: "डेमो डेटा",

highDemand: "उच्च मांग",
mediumDemand: "मध्यम मांग",
veryHighDemand: "बहुत अधिक मांग",
stableDemand: "स्थिर मांग",
Wheat: "गेहूं",
"Rice (Basmati)": "चावल (बासमती)",
Cotton: "कपास",
Soybean: "सोयाबीन",
Maize: "मक्का",
Tomato: "टमाटर",
Onion: "प्याज",
Potato: "आलू",
Sugarcane: "गन्ना",
Turmeric: "हल्दी",
Chilli: "मिर्च",
Groundnut: "मूंगफली",
cropWheat: "गेहूं",
cropRiceBasmati: "चावल (बासमती)",
cropCotton: "कपास",
cropSoybean: "सोयाबीन",
cropMaize: "मक्का",
cropTomato: "टमाटर",
cropOnion: "प्याज",
cropPotato: "आलू",
cropSugarcane: "गन्ना",
cropTurmeric: "हल्दी",
cropChilli: "मिर्च",
cropGroundnut: "मूंगफली",
priceTrendOctMar: "मूल्य रुझान (अक्टूबर–मार्च)",
sixMonthPriceTrends: "6 महीने के मूल्य रुझान",
selectCropPriceHistory: "मूल्य इतिहास देखने के लिए फसल चुनें",
stateWiseCropPrices: "राज्यवार फसल मूल्य",
topCrop: "मुख्य फसल",
rising: "बढ़ रहा है",
falling: "घट रहा है",
demandSupplyTrends: "मांग और आपूर्ति रुझान",
demandLabel: "मांग",
supplyLabel: "आपूर्ति",
weatherImpactCrops: "फसलों पर मौसम का प्रभाव",
favorable: "अनुकूल",
riskAlert: "जोखिम चेतावनी",
monitor: "निगरानी करें",
weeklyFarmingAdvisory: "साप्ताहिक कृषि सलाह",
sowNow: "अभी बोएं",
sowNowCrops: "टमाटर, प्याज, हरी सब्जियां",
harvestReady: "कटाई के लिए तैयार",
harvestReadyCrops: "गेहूं, सरसों, चना",
avoidThisWeek: "इस सप्ताह बचें",
avoidThisWeekCrops: "भारी बारिश वाले क्षेत्रों में कपास",
northIndia: "उत्तर भारत",
southIndia: "दक्षिण भारत",
eastIndia: "पूर्व भारत",
westIndia: "पश्चिम भारत",
centralIndia: "मध्य भारत",

clear: "साफ मौसम",
heavyRain: "भारी बारिश",
partlyCloudy: "आंशिक बादल",
sunny: "धूप",
intermittentRain: "रुक-रुक कर बारिश",

wheatHarvestGood: "गेहूं की कटाई के लिए अच्छा",
cottonRisk: "कपास और मिर्च के लिए जोखिम",
riceModerate: "चावल के लिए मध्यम स्थिति",
groundnutGood: "मूंगफली के लिए अच्छा",
soybeanWatch: "सोयाबीन की नमी पर ध्यान दें",
statePunjab: "पंजाब",
stateUttarPradesh: "उत्तर प्रदेश",
stateMaharashtra: "महाराष्ट्र",
stateMadhyaPradesh: "मध्य प्रदेश",
stateAndhraPradesh: "आंध्र प्रदेश",
stateKarnataka: "कर्नाटक",
stateGujarat: "गुजरात",
stateWestBengal: "पश्चिम बंगाल",
backToCalculators: "कैलकुलेटर पर वापस जाएं",
tractorSubsidySubtitle: "ट्रैक्टर खरीद पर सरकारी सब्सिडी की गणना करें",
profitCalculatorSubtitle: "अपनी खेती का शुद्ध लाभ ज्ञात करें",
quantityQuintalsLabel: "मात्रा (क्विंटल)",
profitResultTitle: "आपका लाभ परिणाम",
mspPriceUsedLabel: "एमएसपी मूल्य उपयोग किया गया",
revenueLabel: "राजस्व",
costLabel: "लागत",
lossLabel: "हानि",
calculateProfit: "लाभ की गणना करें",
region_North_East: "उत्तर-पूर्व",
  marketInsights: "मार्केट इनसाइट्स",
  joinNow: "अभी जुड़ें",
  statesCovered: "कवर किए गए राज्य",
farmersCount: "किसान",
buyersCount: "खरीदार",
marketBidLabel: "मार्केट बोली",
noBids: "कोई बोली नहीं",
basedOnMarketplace: "मार्केटप्लेस के आधार पर",
subsidyResultTitle: "सब्सिडी परिणाम",
subsidySavedMessage: "आपने ₹{amount} की बचत की",
marketplaceSubtitle: "भारत भर के किसानों से ताज़ी फसलों पर सीधे देखें और बोली लगाएँ",
totalListings: "कुल लिस्टिंग",
openForBids: "बोली के लिए खुला",
totalBids: "कुल बोलियाँ",
searchCropsPlaceholder: "फसलें खोजें...",
latest: "नवीनतम",
priceLowHigh: "कम से ज्यादा कीमत",
priceHighLow: "ज्यादा से कम कीमत",
byQuantity: "मात्रा के अनुसार",
allCrops: "सभी फसलें",
grains: "अनाज",
vegetables: "सब्जियां",
fruits: "फल",
cashCrops: "नकदी फसलें",
pulses: "दालें",
showingListings: "{count} लिस्टिंग दिखाई जा रही हैं",
sortedBy: "क्रमबद्ध:",
noListingsAvailable: "अभी कोई लिस्टिंग उपलब्ध नहीं है",
listCropsMessage: "अपनी फसलें डैशबोर्ड से जोड़ें!",
"price-low": "कम से ज्यादा कीमत",
"price-high": "ज्यादा से कम कीमत",
quantity: "मात्रा के अनुसार",
  },
} as const;

type TranslationKeys = keyof typeof translations.en;

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<Lang>("en");

  const t = (key: string): string => {
    const value = (translations[lang] as Record<string, string>)[key];
    return value || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
};
