import React, { createContext, useContext, useState, ReactNode } from "react";

// supported languages
export type Lang = "en" | "hi";

// simple dictionary object; keys should be the same between languages
const translations = {
  en: {
    home: "Home",
    marketplace: "Marketplace",
    cropAdvisory: "Crop Advisory",
    mspCalculator: "Calculator",
    govSchemes: "Gov Schemes",
    myDashboard: "My Dashboard",
    adminPanel: "Admin Panel",
    loginSignup: "Login / Sign Up",
    logout: "Logout",
    // index page samples
    heroTitle: "Kisan Bandhu",
    heroSubtitle: "Empowering Farmers. Connecting Markets.",
    exploreMarketplace: "Explore Marketplace",
    aboutTitle: "About Kisan Bandhu",
    aboutDescription:
      "Kisan Bandhu is India's farmer-first digital marketplace that eliminates middlemen and connects farmers directly with buyers. Our platform ensures fair prices through a transparent bidding system, provides crop advisory services, and helps farmers access government schemes — all in one place.",
    howItWorks: "How It Works",
    readyToGetStarted: "Ready to Get Started?",
    ctaDescription:
      "Join thousands of farmers and buyers on India's most trusted agricultural marketplace.",
    joinKisanBandhu: "Join Kisan Bandhu",
    // marketplace page
    marketplaceTitle: "🏪 Marketplace",
    marketplaceDescription: "Browse and bid on crops from farmers across India",
    pleaseLoginBid: "Please login to place a bid",
    bidSuccess: "Bid placed successfully!",
    onlyBuyer: "Only buyers can place bids.",
    searchPlaceholder: "Search crops...",
    sortLatest: "Latest",
    sortPriceLow: "Price: Low → High",
    sortPriceHigh: "Price: High → Low",
    sortQuantity: "Quantity",
    noCropsFound: "No crops found matching your criteria.",
    // auth page
    welcomeBack: "Welcome Back!",
    createAccountHeader: "Create Account",
    loginPrompt: "Login to your Kisan Bandhu account",
    joinPrompt: "Join Kisan Bandhu today",
    fullNameLabel: "Full Name",
    enterFullName: "Enter your full name",
    emailLabel: "Email",
    enterYourEmail: "Enter your email",
    passwordLabel: "Password",
    enterYourPassword: "Enter your password",
    roleLabel: "I am a",
    farmerRole: "Farmer",
    buyerRole: "Buyer",
    loginButton: "Login",
    createAccountButton: "Create Account",
    dontHaveAccount: "Don't have an account? Sign Up",
    alreadyHaveAccount: "Already have an account? Login",
    errorEmailPassword: "Email and password are required.",
    errorNameRequired: "Name is required.",
    errorPasswordLength: "Password must be at least 6 characters.",
    errorInvalidEmail: "Enter a valid email address.",
    errorInvalidCredentials: "Invalid email or password.",
    errorAccountExists: "Account already exists with this email.",
    // gov schemes page
    governmentSchemesTitle: "🏛️ Government Schemes",
    governmentSchemesDescription: "Important farmer welfare schemes by the Government of India",
    eligibilityLabel: "Eligibility:",
    benefitsLabel: "Benefits:",
    applyNow: "Apply Now →",
    // msp calculator page
    mspCalculatorTitle: "🧮 Calculator",
    mspCalculatorDescription: "Calculate Minimum Support Price value for your harvest",
    selectCropLabel: "Select Crop",
    chooseCropPlaceholder: "Choose a crop",
    quantityLabel: "Quantity (quintals)",
    quantityPlaceholder: "e.g. 50",
    calculateMspButton: "Calculate MSP Value",
    mspValueLabel: "MSP Value",
    marketBidValueLabel: "Market Bid Value",
    basedOnMarket: "Based on current marketplace",
    marketAbove: "✅ Market bid is ₹{diff} above MSP!",
    marketBelow: "⚠️ Market bid is ₹{diff} below MSP. Consider MSP route.",
    noBidsYet: "No bids yet",
    // advisory page
    cropAdvisoryTitle: "🌱 Crop Advisory",
    cropAdvisoryDescription: "Get personalized crop recommendations based on your conditions",
    soilTypeLabel: "Soil Type",
    seasonLabel: "Season",
    regionLabel: "Region",
    selectSoilPlaceholder: "Select Soil",
    selectSeasonPlaceholder: "Select Season",
    selectRegionPlaceholder: "Select Region",
    getRecommendations: "Get Recommendations",
    yieldLabel: "Yield:",
    profitLabel: "Profit:",
    waterLabel: "Water:",
    water_High: "High",
    water_Medium: "Medium",
    water_Low: "Low",
    unit_quintalsPerHectare: "quintals/hectare",
    // generic
    chooseOption: "Choose an option",
    brandName: "Kisan Bandhu",
    brandDescription: "Empowering farmers by connecting them directly to buyers. Fair prices, transparent bidding, better lives.",
    quickLinks: "Quick Links",
    contactUs: "Contact Us",
    followUs: "Follow Us",
    // soil types
    soil_Alluvial: "Alluvial",
    soil_Black_Regur: "Black (Regur)",
    soil_BlackRegur: "Black (Regur)",
    soil_Red: "Red",
    soil_Laterite: "Laterite",
    soil_Sandy: "Sandy",
    soil_Clay: "Clay",
    // seasons
    season_Kharif: "Kharif (Monsoon)",
    season_Rabi: "Rabi (Winter)",
    season_Zaid: "Zaid (Summer)",
    // regions
    region_North: "North",
    region_South: "South",
    region_East: "East",
    region_West: "West",
    region_Central: "Central",
    region_NorthEast: "North-East",
    // crops for msp/advisory
    crop_Wheat: "Wheat",
    crop_Rice: "Rice",
    crop_Maize: "Maize",
    crop_Cotton: "Cotton",
    crop_Sugarcane: "Sugarcane",
    crop_Mustard: "Mustard",
    crop_Chickpea_Chana: "Chickpea (Chana)",
    crop_Soybean: "Soybean",
    crop_MoongDal: "Moong Dal",
    crop_Jowar: "Jowar",
    crop_Bajra: "Bajra",
    crop_Groundnut: "Groundnut",
    // scheme names & descriptions
    scheme_PMKISAN_name: "PM-KISAN",
    scheme_PMKISAN_desc: "Direct income support of ₹6,000 per year to farmer families in three equal installments.",
    scheme_PMKISAN_eligibility: "All land-holding farmer families with cultivable land.",
    scheme_PMKISAN_benefits: "₹6,000/year direct bank transfer, no middlemen involved.",
    scheme_PMFasal_name: "PM Fasal Bima Yojana",
    scheme_PMFasal_desc: "Crop insurance scheme providing financial support against crop loss due to natural calamities.",
    scheme_PMFasal_eligibility: "All farmers growing notified crops in notified areas.",
    scheme_PMFasal_benefits: "Low premium rates: 2% for Kharif, 1.5% for Rabi, 5% for commercial crops.",
    scheme_SoilHealth_name: "Soil Health Card Scheme",
    scheme_SoilHealth_desc: "Provides soil health cards with crop-wise nutrient recommendations to farmers.",
    scheme_SoilHealth_eligibility: "All farmers across India.",
    scheme_SoilHealth_benefits: "Free soil testing, personalized fertilizer recommendations, improved yield.",
    scheme_KCC_name: "Kisan Credit Card (KCC)",
    scheme_KCC_desc: "Provides affordable credit to farmers for cultivation, post-harvest, and consumption needs.",
    scheme_KCC_eligibility: "Farmers, fishermen, and animal husbandry farmers.",
    scheme_KCC_benefits: "Credit up to ₹3 lakh at 4% interest, crop insurance coverage included.",
    scheme_eNAM_name: "e-NAM (National Agriculture Market)",
    scheme_eNAM_desc: "Online trading platform for agricultural commodities to ensure better prices for farmers.",
    scheme_eNAM_eligibility: "Registered farmers and traders.",
    scheme_eNAM_benefits: "Transparent price discovery, reduced middlemen, wider market access.",
    scheme_PMKrishi_name: "PM Krishi Sinchai Yojana",
    scheme_PMKrishi_desc: "Ensures access to water for irrigation with 'Har Khet Ko Pani' initiative.",
    scheme_PMKrishi_eligibility: "All farmers with focus on water-scarce areas.",
    scheme_PMKrishi_benefits: "Subsidized micro-irrigation, drip irrigation systems, water harvesting support.",
    // dashboard & general UI
    farmerDashboardTitle: "🧑‍🌾 Farmer Dashboard",
    buyerDashboardTitle: "🛒 Buyer Dashboard",
    adminPortalTitle: "⚙️ Admin Portal",
    adminPortalDesc: "Platform overview and management",
    welcomeUser: "Welcome, {name}",
    addCrop: "Add Crop",
    listNewCrop: "List a New Crop",
    cropNameLabel: "Crop Name",
    cropNamePlaceholder: "e.g. Wheat",
    cropTypeLabel: "Crop Type",
    cropType_grain: "Grain",
    cropType_vegetable: "Vegetable",
    cropType_fruit: "Fruit",
    cropType_cash_crop: "Cash Crop",
    cropType_pulse: "Pulse",
    market_crop_all: "All Crops",
    market_crop_grain: "🌾 Grains",
    market_crop_vegetable: "🥬 Vegetables",
    market_crop_fruit: "🍎 Fruits",
    market_crop_cash_crop: "🌿 Cash Crops",
    market_crop_pulse: "🫘 Pulses",
    basePriceLabel: "Base Price (₹/quintal)",
    basePricePlaceholder: "e.g. 2200",
    listCropButton: "List Crop",
    cancel: "Cancel",
    status_Open: "Open",
    status_Sold: "Sold",
    viewBids: "Bids",
    acceptBest: "Accept Best",
    errorFillAllFields: "Fill all fields.",
    successCropListed: "Crop listed successfully!",
    successBidAccepted: "Bid accepted! Crop marked as sold.",
    myBidHistory: "My Bid History",
    myBestBidLabel: "My best bid:",
    highestLabel: "Highest:",
    wonStatus: "Won! 🎉",
    lostStatus: "Lost",
    availableCrops: "Available Crops",
    //tractorSubsidy
    tractorSubsidyTitle: "Tractor Subsidy Calculator",
tractorPriceLabel: "Tractor Price (₹)",
enterTractorPrice: "Enter tractor price",
farmerCategoryLabel: "Farmer Category",
selectCategory: "Select Category",
calculateSubsidy: "Calculate Subsidy",
governmentSubsidy: "Government Subsidy",
finalPriceAfterSubsidy: "Final Price After Subsidy",
    // marketplace card labels
  
    card_base: "Base price:",
    card_highestBid: "Highest bid:",
    card_yourBidPlaceholder: "Your bid (₹)",
    card_bidButton: "Bid",

    successBidPlaced: "Bid placed successfully!",
    admin_statTotalUsers: "Total Users",
    admin_statTotalListings: "Total Listings",
    admin_statTotalBids: "Total Bids",
    admin_statOpenSold: "Open / Sold",
    registeredUsers: "Registered Users",
    nameHeader: "Name",
    emailHeader: "Email",
    roleHeader: "Role",
    noUsersYet: "No users registered yet.",
    allCropListings: "All Crop Listings",
    byLabel: "by",
    listingRemoved: "Listing removed",
    removeBtn: "Remove",
    adminAccessRequired: "Admin access required.",
    bidsSuffix: "bid(s)",
    noListingsMessage: "You haven't listed any crops yet. Click \"Add Crop\" to get started!",
  },
  hi: {
    home: "होम",
    marketplace: "मार्केटप्लेस",
    cropAdvisory: "फसल सलाह",
    mspCalculator: "कैलकुलेटर",
    govSchemes: "सरकारी योजनाएँ",
    myDashboard: "मेरा डैशबोर्ड",
    adminPanel: "प्रशासन पैनल",
    loginSignup: "लॉगिन / साइन अप",
    logout: "लॉगआउट",
    // index page samples
    heroTitle: "किसान बंधु",
    heroSubtitle: "किसानों को सशक्त बनाना। बाजारों को जोड़ना।",
    exploreMarketplace: "मार्केटप्लेस देखें",
    aboutTitle: "किसान बंधु के बारे में",
    aboutDescription:
      "किसान बंधु भारत का किसान-प्रथम डिजिटल मार्केटप्लेस है जो दलालों को हटाकर किसानों को सीधे खरीदारों से जोड़ता है। हमारी प्लेटफ़ॉर्म पारदर्शी बोली प्रणाली के माध्यम से उचित मूल्य सुनिश्चित करती है, फसल सलाह सेवाएँ प्रदान करती है, और किसानों को सरकारी योजनाओं तक पहुँचने में मदद करती है — एक ही स्थान पर।",
    howItWorks: "यह कैसे काम करता है",
    readyToGetStarted: "शुरू करने के लिए तैयार?",
    ctaDescription:
      "भारत के सबसे विश्वसनीय कृषि बाजार पर हजारों किसानों और खरीदारों से जुड़ें।",
    joinKisanBandhu: "किसान बंधु में शामिल हों",
    // marketplace page translations
    marketplaceTitle: "🏪 मार्केटप्लेस",
    marketplaceDescription: "भारत भर के किसानों से फसलों पर नीलामी करें और बोली लगाएं",
    pleaseLoginBid: "बोली लगाने के लिए कृपया लॉगिन करें",
    bidSuccess: "बोली सफलतापूर्वक लगाई गई!",
    onlyBuyer: "केवल खरीदार बोली लगा सकते हैं।",
    searchPlaceholder: "फसलों की खोज करें...",
    sortLatest: "नवीनतम",
    sortPriceLow: "कीमत: कम → अधिक",
    sortPriceHigh: "कीमत: अधिक → कम",
    sortQuantity: "मात्रा",
    noCropsFound: "आपकी शर्तों के अनुरूप कोई फसल नहीं मिली।",
    // auth page translations
    welcomeBack: "वापसी पर स्वागत है!",
    createAccountHeader: "खाता बनाएं",
    loginPrompt: "अपने किसान बंधु खाते में लॉगिन करें",
    joinPrompt: "आज किसान बंधु में शामिल हों",
    fullNameLabel: "पूरा नाम",
    enterFullName: "अपना पूरा नाम दर्ज करें",
    emailLabel: "ईमेल",
    enterYourEmail: "अपना ईमेल दर्ज करें",
    passwordLabel: "पासवर्ड",
    enterYourPassword: "अपना पासवर्ड दर्ज करें",
    roleLabel: "मैं एक हूँ",
    farmerRole: "किसान",
    buyerRole: "खरीदार",
    loginButton: "लॉगिन",
    createAccountButton: "खाता बनाएं",
    dontHaveAccount: "खाता नहीं है? साइन अप करें",
    alreadyHaveAccount: "पहले से एक खाता है? लॉगिन करें",
    errorEmailPassword: "ईमेल और पासवर्ड आवश्यक हैं।",
    errorNameRequired: "नाम आवश्यक है।",
    errorPasswordLength: "पासवर्ड कम से कम 6 अक्षरों का होना चाहिए।",
    errorInvalidEmail: "एक वैध ईमेल पता दर्ज करें।",
    errorInvalidCredentials: "अमान्य ईमेल या पासवर्ड।",
    errorAccountExists: "इस ईमेल के साथ पहले से एक खाता मौजूद है।",
    // gov schemes page translations
    governmentSchemesTitle: "🏛️ सरकारी योजनाएँ",
    governmentSchemesDescription: "भारत सरकार द्वारा महत्वपूर्ण किसान कल्याण योजनाएँ",
    eligibilityLabel: "योग्यता:",
    benefitsLabel: "लाभ:",
    applyNow: "अब आवेदन करें →",
    // msp calculator page translations
    mspCalculatorTitle: "🧮 कैलकुलेटर",
    mspCalculatorDescription: "अपने फसल के लिए न्यूनतम समर्थन मूल्य की गणना करें",
    selectCropLabel: "फसल चुनें",
    chooseCropPlaceholder: "फसल चुनें",
    quantityLabel: "मात्रा (क्विंटल)",
    quantityPlaceholder: "जैसे 50",
    calculateMspButton: "एमएसपी मान की गणना करें",
    mspValueLabel: "एमएसपी मूल्य",
    marketBidValueLabel: "बाजार बोली मूल्य",
    basedOnMarket: "वर्तमान बाज़ार के आधार पर",
    marketAbove: "✅ बाजार बोली MSP से ₹{diff} ऊपर है!",
    marketBelow: "⚠️ बाजार बोली MSP से ₹{diff} नीचे है। MSP मार्ग पर विचार करें।",
    noBidsYet: "अभी तक कोई बोली नहीं",
    //tractorSubsidy
    tractorSubsidyTitle: "ट्रैक्टर सब्सिडी कैलकुलेटर",
tractorPriceLabel: "ट्रैक्टर की कीमत (₹)",
enterTractorPrice: "ट्रैक्टर की कीमत दर्ज करें",
farmerCategoryLabel: "किसान श्रेणी",
selectCategory: "श्रेणी चुनें",
calculateSubsidy: "सब्सिडी की गणना करें",
governmentSubsidy: "सरकारी सब्सिडी",
finalPriceAfterSubsidy: "सब्सिडी के बाद अंतिम कीमत",
    // advisory page translations
    cropAdvisoryTitle: "🌱 फसल सलाह",
    cropAdvisoryDescription: "आपकी परिस्थितियों के आधार पर व्यक्तिगत रूप से फसल की सिफारिशें प्राप्त करें",
    soilTypeLabel: "मिट्टी का प्रकार",
    seasonLabel: "मौसम",
    regionLabel: "क्षेत्र",
    selectSoilPlaceholder: "मिट्टी चुनें",
    selectSeasonPlaceholder: "मौसम चुनें",
    selectRegionPlaceholder: "क्षेत्र चुनें",
    getRecommendations: "अनुशंसाएँ प्राप्त करें",
    yieldLabel: "उपज:",
    profitLabel: "लाभ:",
    waterLabel: "पानी:",
    water_High: "उच्च",
    water_Medium: "मध्यम",
    water_Low: "निम्न",
    unit_quintalsPerHectare: "क्विंटल/हेक्टेयर",
    // generic
    chooseOption: "एक विकल्प चुनें",
    brandName: "किसान बंधु",
    brandDescription: "किसानों को सीधे खरीदारों से जोड़कर उन्हें सशक्त बनाना। उचित मूल्य, पारदर्शी बोली, बेहतर जीवन।",
    quickLinks: "त्वरित लिंक",
    contactUs: "संपर्क करें",
    followUs: "हमें फॉलो करें",
    // soil types
    soil_Alluvial: "आलुवियल",
    soil_Black_Regur: "ब्लैक (रेगूर)",
    soil_BlackRegur: "ब्लैक (रेगूर)",
    soil_Red: "लाल",
    soil_Laterite: "लेटेराइट",
    soil_Sandy: "रेतीली",
    soil_Clay: "मिट्टी",
    // seasons
    season_Kharif: "खरीफ (मानसून)",
    season_Rabi: "रबी (सर्दी)",
    season_Zaid: "ज़ैद (गर्मी)",
    // regions
    region_North: "उत्तर",
    region_South: "दक्षिण",
    region_East: "पूर्व",
    region_West: "पश्चिम",
    region_Central: "केंद्रीय",
    region_NorthEast: "उत्तर-पूर्व",
    // crops for msp/advisory
    crop_Wheat: "गेहूँ",
    crop_Rice: "चावल",
    crop_Maize: "मक्का",
    crop_Cotton: "कपास",
    crop_Sugarcane: "गन्ना",
    crop_Mustard: "सरसों",
    crop_Chickpea_Chana: "चना (काबुली)",
    crop_Soybean: "सोयाबीन",
    crop_MoongDal: "मूंग दाल",
    crop_Jowar: "ज्वार",
    crop_Bajra: "बाजरा",
    crop_Groundnut: "मूंगफली",
    // scheme names & descriptions
    scheme_PMKISAN_name: "PM-KISAN",
    scheme_PMKISAN_desc: "किसान परिवारों को तीन समान किस्तों में प्रति वर्ष ₹6,000 की प्रत्यक्ष आय सहायता।",
    scheme_PMFasal_name: "PM फसल बीमा योजना",
    scheme_PMFasal_desc: "प्राकृतिक आपदाओं के कारण फसल नुकसान के खिलाफ वित्तीय सहायता प्रदान करने वाली फसल बीमा योजना।",
    scheme_SoilHealth_name: "मृदा स्वास्थ्य कार्ड योजना",
    scheme_SoilHealth_desc: "किसानों को फसल-वार पोषक तत्व अनुशंसियों के साथ मृदा स्वास्थ्य कार्ड प्रदान करती है।",
    scheme_KCC_name: "किसान क्रेडिट कार्ड (KCC)",
    scheme_KCC_desc: "खेती, फसलोपरांत और उपभोग आवश्यकताओं के लिए कृषि ऋण प्रदान करता है।",
    scheme_eNAM_name: "e-NAM (राष्ट्रीय कृषि बाज़ार)",
    scheme_eNAM_desc: "किसानों को बेहतर मूल्य सुनिश्चित करने के लिए कृषि वस्तुओं के लिए ऑनलाइन व्यापार मंच।",
    scheme_PMKrishi_name: "पीएम कृषि सिंचाई योजना",
    scheme_PMKrishi_desc: "'हर खेत को पानी' पहल के साथ सिंचाई के लिए पानी की पहुंच सुनिश्चित करता है।",
    // scheme eligibility/benefits in Hindi
    scheme_PMKISAN_eligibility: "उपयोग करने के लिए जमीनी संपत्ति वाले सभी किसान परिवार।",
    scheme_PMKISAN_benefits: "₹6,000/वर्ष सीधे बैंक खाते में, कोई दलाल नहीं।",
    scheme_PMFasal_eligibility: "सूचित क्षेत्रों में सूचित फसलें उगाने वाले सभी किसान।",
    scheme_PMFasal_benefits: "कम प्रीमियम दरें: खरीफ 2%, रबी 1.5%, वाणिज्यिक फसलों पर 5%।",
    scheme_SoilHealth_eligibility: "भारत भर के सभी किसान।",
    scheme_SoilHealth_benefits: "मुक्त मिट्टी परीक्षण, व्यक्तिगत उर्वरक सिफारिशें, बेहतर उपज।",
    scheme_KCC_eligibility: "किसान, मछुआरे, और पशुपालन किसान।",
    scheme_KCC_benefits: "₹3 लाख तक 4% ब्याज पर ऋण, फसल बीमा कवर सहित।",
    scheme_eNAM_eligibility: "पंजीकृत किसान और व्यापारी।",
    scheme_eNAM_benefits: "पारदर्शी मूल्य निर्धारण, कम दलाल, व्यापक बाजार पहुंच।",
    scheme_PMKrishi_eligibility: "पानी की कमी वाले क्षेत्रों पर ध्यान देने वाले सभी किसान।",
    scheme_PMKrishi_benefits: "सब्सिडी माइक्रो-सिंचाई, ड्रिप सिस्टम, जल संचयन सहायता।",
    // dashboard & general UI
    farmerDashboardTitle: "🧑‍🌾 किसान डैशबोर्ड",
    buyerDashboardTitle: "🛒 खरीदार डैशबोर्ड",
    adminPortalTitle: "⚙️ प्रशासन पोर्टल",
    adminPortalDesc: "प्लेटफ़ॉर्म अवलोकन और प्रबंधन",
    welcomeUser: "स्वागत है, {name}",
    addCrop: "फसल जोड़ें",
    listNewCrop: "नई फसल सूचीबद्ध करें",
    cropNameLabel: "फसल का नाम",
    cropNamePlaceholder: "जैसे गेहूँ",
    cropTypeLabel: "फसल का प्रकार",
    cropType_grain: "अनाज",
    cropType_vegetable: "सब्ज़ी",
    cropType_fruit: "फल",
    cropType_cash_crop: "नकदी फसल",
    cropType_pulse: "दाल",
    market_crop_all: "सभी फसलें",
    market_crop_grain: "🌾 अनाज",
    market_crop_vegetable: "🥬 सब्ज़ियाँ",
    market_crop_fruit: "🍎 फल",
    market_crop_cash_crop: "🌿 नकदी फसलें",
    market_crop_pulse: "🫘 दालें",
    basePriceLabel: "मूल्य (₹/क्विंटल)",
    basePricePlaceholder: "जैसे 2200",
    listCropButton: "फसल सूचीबद्ध करें",
    cancel: "रद्द करें",
    status_Open: "खुला",
    status_Sold: "बिक चुका",
    viewBids: "बोली",
    acceptBest: "सर्वोत्तम स्वीकार करें",
    errorFillAllFields: "सभी फ़ील्ड भरें।",
    successCropListed: "फसल सफलतापूर्वक सूचीबद्ध की गई!",
    successBidAccepted: "बोली स्वीकार की गई! फसल बेची हुई के रूप में चिह्नित।",
    myBidHistory: "मेरी बोली इतिहास",
    myBestBidLabel: "मेरी सर्वोत्तम बोली:",
    highestLabel: "सर्वोच्च:",
    wonStatus: "जीत गए! 🎉",
    lostStatus: "हार गए",
    availableCrops: "उपलब्ध फसलें",
    successBidPlaced: "बोली सफलतापूर्वक लगाई गई!",
    admin_statTotalUsers: "कुल उपयोगकर्ता",
    admin_statTotalListings: "कुल सूचीबद्धियाँ",
    admin_statTotalBids: "कुल बोलियाँ",
    admin_statOpenSold: "खुला / बिका",
    card_base: "मूल्य:",
    card_highestBid: "उच्चतम बोली:",
    card_yourBidPlaceholder: "आपकी बोली (₹)",
    card_bidButton: "बोली",
    registeredUsers: "पंजीकृत उपयोगकर्ता",
    nameHeader: "नाम",
    emailHeader: "ईमेल",
    roleHeader: "भूमिका",
    noUsersYet: "कोई उपयोगकर्ता अभी तक पंजीकृत नहीं।",
    allCropListings: "सभी फसल सूचीबद्धियाँ",
    byLabel: "द्वारा",
    listingRemoved: "सूची हटाई गई",
    removeBtn: "हटाएँ",
    adminAccessRequired: "प्रशासन पहुंच आवश्यक है।",
    bidsSuffix: "बोली",
    noListingsMessage: "आपने अभी तक कोई फसल सूचीबद्ध नहीं की है। शुरू करने के लिए \"फसल जोड़ें\" पर क्लिक करें!",
  },
} as const;

type TranslationKeys = keyof typeof translations.en;

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: TranslationKeys) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<Lang>("en");

  const t = (key: TranslationKeys) => {
    const value = translations[lang][key];
    return value || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
};
